vendor = "Cisco"
name = "Cisco Catalyst SD-WAN Controller 认证绕过漏洞"
type = "认证绕过"
version = "20.19.1"
detail = """https://github.com/fangbarristerbar/CVE-2026-20182-POC
https://github.com/portbuster1337/CVE-2026-20182"""
fix = "升级至 20.19.1+；禁止 UDP 12346 对外暴露"
date = 20260514
label = "nday"
cve = "CVE-2026-20182"
verifier = "AdySec"
