vendor = "cisco"
name = "Cisco Unified Communications 多产品代码注入漏洞"
type = "代码注入"
path = "/vmrest/"
version = "12.6"
detail = """POST /vmrest/ HTTP/1.1 Host: target <ysoserial payload>
POST /cucemapi/ HTTP/1.1 Host: target <ysoserial payload>
POST /ccm100/ HTTP/1.1 Host: target <ysoserial payload>"""
fix = "升级至 15SU2 / 12.6(2)ES04"
date = 20260121
label = "nday"
cve = "CVE-2026-20045"
verifier = "AdySec"
