vendor = "WinRAR"
name = "WinRAR 7.23 修复内存溢出与路径遍历漏洞"
type = "缓冲区溢出"
version = "26.02"
detail = "https://github.com/advisories/ghsa-5hjj-fvq6-8j36"
fix = "升级至 >= 7.23"
date = 20260701
label = "nday"
cve = "CVE-2026-14191"
verifier = "AdySec"
