vendor = "东方通"
name = "东方通 TongWeb 应用服务器 ejbserver EJB 反序列化远程代码执行漏洞"
type = "反序列化"
path = "/ejbserver/ejb"
version = "6.1.8"
detail = """POST /ejbserver/ejb HTTP/1.1 Host: target:8088 Content-Type: application/x-java-serialized-object

[OEJP/1.1 + 序列化数据]"""
fix = "升级至官方补丁"
date = 20251105
label = "nday"
cve = "QVD-2025-44295"
verifier = "AdySec"
