vendor = "XWiki"
name = "XWiki getdeleteddocuments.vm SQL注入"
type = "SQL注入"
version = "未知"
path = "/xwiki/rest/liveData/sources/liveTable/entries"
detail = "未知"
fix = "未知"
date = "0729"
label = "nday"
verifier = "AdySec"
