vendor = "东胜物流"
name = "东胜物流软件 DsWebService.asmx SQL注入"
type = "SQL注入"
version = "未知"
path = "/webservice/DsWebService.asmx"
detail = "GetSeaiBsData、GetSeaeBsDataList、GetSeaeBsData和GetSeaiBsDataList、LoadCustomMainfastStatus、GetSeaiData方法"
fix = "暂无"
date = "0729"
label = "nday"
verifier = "AdySec"
