vendor = "华天动力"
name = "华天软件inforcenter PLM前台文件上传"
type = "RCE"
version = "未知"
path = "/Base/BaseHandler.ashx"
detail = "/Base/BaseHandler.ashx?type=uploadFileToIIS&uploadPath=../Files/"
fix = "22年的洞，某厂商新发的情报"
date = "0704"
label = "0day"
verifier = "AdySec"
