vendor = "泛微"
name = "泛微E-cology9 SQL注入"
type = "SQL注入"
version = "<10.75"
path = "/js/hrm/getdata.jsp?cmd=savect /js/hrm/getdata.jsp?cmd=initChart"
detail = "URL二次编码"
fix = "https://www.weaver.com.cn/cs/securityDownload.html?src=cn"
date = "0701"
label = "0day"
verifier = "AdySec"
