vendor = "浪潮"
name = "浪潮GS的restfulserviceforweb.asmx存在sql注入"
type = "SQL注入"
version = "未知"
path = "/restfulserviceforweb.asmx"
detail = "未知"
fix = "未知"
date = "0714"
label = "0day"
verifier = "AdySec"
