vendor = "用友"
name = "用友NC deleteEvent SQL注入"
type = "SQL注入"
version = "未知"
path = "/portal/pt/oacoSchedulerEvents/deleteEvent"
detail = "未知"
fix = "未知"
date = "0708"
label = "1day"
verifier = "AdySec"
