vendor = "用友"
name = "用友 U8 CRM客户关系管理系统 checkselectpartapply.php 接口存在SQL注入"
type = "SQL注入"
version = "未知"
path = "checkselectpartapply.php"
detail = "未知"
fix = "缺省规则可检出"
date = "0730"
label = "1day"
verifier = "AdySec"
