vendor = "用友"
name = "用友畅捷通TPLUS AccountClearControler SQL注入"
type = "SQL注入"
version = "未知"
path = "/tplus/ajaxpro/Ufida.T.SM.UIP.Tool.AccountClearControler,Ufida.T.SM.UIP.ashx"
detail = "/tplus/ajaxpro/Ufida.T.SM.UIP.Tool.AccountClearControler,Ufida.T.SM.UIP.ashx?method=GetisInitBCRetail"
fix = "老洞新用"
date = "0707"
label = "0day"
verifier = "AdySec"
