vendor = "索贝"
name = "索贝内容管理系统 /search/full-search 信息泄露"
type = "信息泄露"
version = "未知"
path = "/search/full-search"
detail = "/search/full-search"
fix = "使用WAF封禁该地址"
date = "0730"
label = "nday"
verifier = "AdySec"
