vendor = "美特"
name = "美特CRMdruid未授权访问"
type = "权限绕过"
version = "未知"
path = "/druid/websession.html"
detail = "/druid/websession.html"
fix = "添加访问控制策略"
date = "0707"
label = "nday"
verifier = "AdySec"
