vendor = "联想"
name = "联想网盘FileZ filez/user/getUserSession任意用户登录"
type = "权限绕过"
version = "信创版"
path = "/v2/user/xxxxx"
detail = "未公开，但不是权限绕过，此处@sxf，分类不准"
fix = "无修复方案，联想嘴硬中"
date = "0704"
label = "0day"
verifier = "AdySec"
