vendor = "联软"
name = "联软UniSDP 零信任访问控制系统 /emm-core/oauth/token 信息泄露"
type = "信息泄露"
version = "未知"
path = "/emm-core/oauth/token"
detail = "/emm-core/oauth/token"
fix = "使用WAF封禁该地址"
date = "0724"
label = "0day"
verifier = "AdySec"
