vendor = "金蝶"
name = "金蝶 Apusic 应用中间件远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/admin/protect/datasource/createDataSource"
detail = "懂得都懂"
fix = "23年老洞"
date = "0704"
label = "nday"
verifier = "AdySec"
