vendor = "雄伟"
name = "雄伟科技智慧食堂系统任意用户密码重置"
type = "权限绕过"
version = "未知"
path = "/Account/ForgetPasswordJson"
detail = "/Account/ForgetPasswordJson"
fix = "垃圾洞"
date = "0703"
label = "nday"
verifier = "AdySec"
