vendor = "Apache"
name = "Apache ActiveMQ远程命令执行漏洞"
type = "RCE"
version = "5.18.0<=Apache ActiveMQ<5.18.3 5.17.0<=Apache ActiveMQ<5.17.6 5.16.0<=Apache ActiveMQ<5.16.7 5.15.0<=Apache ActiveMQ<5.15.15"
path = "git自己搜"
detail = "https://github.com/Hutt0n0/ActiveMqRCE"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
