vendor = "CAGI"
name = "某U挖矿质押单语言系统前台未授权修改管理员密码"
type = "未授权访问"
version = "未知"
path = "/admin/login/setpassword"
detail = "/admin/login/setpassword"
fix = "WAF封禁路路径，等待发布补丁"
date = "0829"
label = "1day"
