vendor = "TOTOLINK"
name = "TOTOLINK多个版本存在泄漏账号密码"
type = "信息泄露"
version = "未知"
path = "/cgi-bin/ExportSettings.sh"
detail = "/cgi-bin/ExportSettings.sh"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
