vendor = "万户"
name = "万户协同办公平台ezoffice DocumentEdit_unite.jsp SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/defaultroot/public/iWebOfficeSign/DocumentEdit_unite.jsp;?RecordID=1"
detail = "/defaultroot/public/iWebOfficeSign/DocumentEdit_unite.jsp;?RecordID=1"
fix = "使用WAF进行拦截"
date = "0724"
label = "nday"
