vendor = "山石网科"
name = "山石网科堡垒机存在远程代码执行漏洞0day（实际为去年老洞）"
type = "RCE"
version = "未知"
path = "/rest/v1/trusted_hosts"
detail = "山石运维安全网关是集运维管理与运维审计为一体的堡垒机设备，实现对核心资产的统一认证、统一授权、统一审计，全方位提升运维风险控制能力。由于该软件的 Web 应用对用户的输入未进行有效过滤，直接拼接系统命令执行，造成了远程代码执行漏洞。攻击者可通过构造恶意请求，拼接命令执行任意代码，控制服务器。"
fix = "升级系统版本"
date = "0726"
label = "nday"
