vendor = "拓尔思"
name = "拓尔思-TRSWAS5.0-PermissionAC文件上传"
type = "RCE"
version = "5.0"
path = "/mas/servlets/uploadThumb?appKey=sv&uploading=1"
detail = "/mas/servlets/uploadThumb?appKey=sv&uploading=1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
