vendor = "海康威视"
name = "海康威视教育综合安防管理系统admintoken泄露"
type = "未授权访问"
version = "未知"
path = "/portal/conf/config.properties"
detail = "/portal/conf/config.properties"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "0day"
