vendor = "甄云"
name = "甄云 SRM 云平台 SpEL 表达式注入漏洞"
type = "SQL注入"
version = "未知"
path = "/oauth/public/SpEL表达式/ab?username=bHM="
detail = "/oauth/public/SpEL表达式/ab?username=bHM="
fix = "WAF封禁路路径，等待发布补丁"
date = "0731"
label = "1day"
