vendor = "甄云"
name = "甄云-SRM云平台 -JNDI注入"
type = "RCE"
version = "未知"
path = "/oauth/public/SpEL表达式/ab?username=bHM="
detail = "/oauth/public/SpEL表达式/ab?username=bHM="
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
