vendor = "紫光"
name = "紫光-电子档案管理系统-PermissionAC"
type = "RCE"
version = "未知"
path = "/Archive/ErecordOffice/openOfficeFile"
detail = "/Archive/ErecordOffice/openOfficeFile"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
