vendor = "网件"
name = "Netgear WN604无线路由器siteSurvey.php存在未授权访问漏洞"
type = "未授权访问"
version = "未知"
path = "/siteSurvey.php"
detail = "/siteSurvey.php"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
