vendor = "联软"
name = "联软 UniSDP 零信任访问控制系统 jwt token 泄露漏洞"
type = "信息泄露"
version = "未知"
path = "/emm-core/oauth/token"
detail = "GET /emm-core/oauth/token HTTP/1.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0808"
label = "1day"
