vendor = "金蝶"
name = "金蝶-云星空-SQL注入"
type = "SQL注入"
version = "未知"
path = "/K3Cloud/Kingdee.BOS.ServiceFacade.ServicesStub.Account.AccountService.GetDataCenterList.common.kdsvc"
detail = "/K3Cloud/Kingdee.BOS.ServiceFacade.ServicesStub.Account.AccountService.GetDataCenterList.common.kdsvc"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
