vendor = "锐捷"
name = "锐捷RG-NBS2026G-P交换机存在未授权访问漏洞"
type = "未授权访问"
version = "RG-NBS2026G-P"
path = "/system/passwdManage.htm"
detail = "/system/passwdManage.htm"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
