vendor = "锐捷"
name = "锐捷 RG-NBS2026G-P 交换机WEB 管理ping.htm未授权访问漏洞"
type = "未授权访问"
version = "未知"
path = "/safety/ping.htm"
detail = "/safety/ping.htm"
fix = "WAF封禁路径，等待发布补丁"
date = "0722"
label = "nday"
