vendor = "雄威"
name = "杭州雄威餐厅数字化综合管理平台存在存在绕过认证导致任意密码重置漏洞"
type = "未授权访问"
version = "未知"
path = "/Account/ForgetUser"
detail = "重置密码处，改回包中的code字段为1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0731"
label = "nday"
