vendor = "用友"
name = "用友NC uploadControl/uploadFile 任意文件上传"
type = "任意文件上传"
source = "微信群"
info = "/mp/loginxietong?username= /mp/uploadControl/uploadFile /mp/uploadFileDir/"
date = "08.11"
label = "0day"
