vendor = "IBM"
name = "IBM WebSphere Application Server远程代码执行"
type = "RCE"
version = "8.5-8.5.5.27、9.0-9.0.5.24"
path = "未知"
detail = "未知"
fix = "https://www.ibm.com/support/pages/node/7237967"
date = "0701"
label = "1day"
verifier = "AdySec"
