vendor = "JieLink"
name = "JieLink + 智能终端操作平台 DeletelpPool SQL 注入"
type = "SQL注入"
version = "未知"
path = "/project/IPPool/DeletelpPool"
detail = "未公开"
fix = "缺省规则可检出"
date = "0718"
label = "0day"
verifier = "AdySec"
