vendor = "东胜物流"
name = "东胜物流软件 WorkFlowGridSource.aspx SQL注入"
type = "SQL注入"
version = "未知"
path = "/workflow/WorkFlowGridSource.aspx"
detail = "未知"
fix = "缺省规则可检出"
date = "0723"
label = "nday"
verifier = "AdySec"
