vendor = "东胜物流"
name = "东胜物流软件WorkFlowGridSource.aspx SQL注入"
type = "SQL注入"
version = "未知"
path = "/WorkFlow/WorkFlowGridSource.aspx"
detail = "未公开"
fix = "缺省规则可检出"
date = "0719"
label = "nday"
verifier = "AdySec"
