vendor = "中科汇联"
name = "中科汇联EasySite系统XStream反序列化"
type = "RCE"
version = "未知"
path = "/eportal/ui?portal.url=/portlet/wx-message0accept!accept.protlet&moduleId=0"
detail = "未知"
fix = "未知"
date = "0703"
label = "1day"
verifier = "未验真"
