vendor = "华天动力"
name = "华天软件-前台文件上传"
type = "文件上传"
version = "最新版"
path = "/Base/BaseHandler.ashx"
detail = "/Base/BaseHandler.ashx?type=uploadFileBase64&fileSupport=ashx"
fix = "不确定真假"
date = "0705"
label = "0day"
verifier = "未验真"
