vendor = "南昊"
name = "南昊网上阅卷系统biaozhi_paper.jsp SQL注入"
type = "SQL注入"
version = "未知"
path = "/exam/admin/chaxun/biaozhi_paper.jsp"
detail = "未知"
fix = "缺省规则可检出"
date = "0724"
label = "1day"
verifier = "AdySec"
