vendor = "圣博润"
name = "圣博润堡垒机远程代码执行"
type = "RCE"
version = "版本≤3.0.11_20231222 3.0.12≤版本≤3.0.12_20240823"
path = "/fort/portal_login"
detail = "未公开"
fix = "24年老洞，但一直没公开，已有补丁"
date = "0703"
label = "nday"
verifier = "AdySec"
