vendor = "天锐"
name = "天锐绿盾审批系统 sysadmin 信息泄露"
type = "信息泄露"
version = "未知"
path = "/trwfe/service/../ws/identity/user/sysadmin"
detail = "/trwfe/service/../ws/identity/user/sysadmin"
fix = "暂无"
date = "0729"
label = "1day"
verifier = "AdySec"
