vendor = "数字通"
name = "数字通 /mobile /document /update parase 存在sql注入"
type = "SQL注入"
version = "未知"
path = "/mobile /document /update parase"
detail = "未知"
fix = "未知"
date = "0714"
label = "0day"
verifier = "AdySec"
