vendor = "昂捷"
name = "昂捷CRM系统cwsuploadpicture任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/enjoyRMIS_WS/WS/Common/cwsuploadpicture.asmx"
detail = "未知"
fix = "未知"
date = "0714"
label = "0day"
verifier = "AdySec"
