vendor = "汉王"
name = "汉王 e 脸通综合管理平台loginOn.do任意文件读取漏洞"
type = "权限绕过"
version = "未知"
path = "/manage/login/loginOn.do/..;/..;/visitorMapConfig/uploadMapFile.do"
detail = "https://github.com/adysec/nuclei_poc/blob/d5b726524f28b7e302e0d3408342f519db88b600/poc/upload/hanwang-uploadMapFile-file-upload.yaml#L23"
fix = "服气，又是老洞"
date = "0705"
label = "nday"
verifier = "sxf"
