vendor = "汉王"
name = "汉王e脸通综合管理平台uploadMeetingFile.do任意文件上传"
type = "RCE"
version = "未知"
path = "/manage/mobiMeetingApp/uploadMeetingFile.do"
detail = "未公开"
fix = "未知"
date = "0721"
label = "1day"
verifier = "AdySec"
