vendor = "泛微"
name = "泛微ecology9 FormmodeFieldBrowserServlet接口存在sql注入"
type = "SQL注入"
version = "未知"
path = "/weaver/weaver.formmode.setup.FormmodeFieldBrowserServlet /weaver/weaver/weaver.formmode.setup.FormmodeFieldBrowserServlet/xlogin/xOfficeServerxjsp /weaver/weaver.formmode.setup.FormmodeFieldBrowserServlet/xlogin/xOfficeServerxjsp"
detail = "未公开"
fix = "未知"
date = "0702"
label = "1day"
verifier = "AdySec"
