vendor = "泛微"
name = "泛微jdbc反序列化"
type = "RCE"
version = "未知"
path = "/api/integration/datasource/add /api/integration/datasource/update"
detail = "据说是spring.datasource导致的"
fix = "未知"
date = "0704"
label = "0day"
verifier = "未验真"
