vendor = "浪潮"
name = "浪潮GSP企业管理软件 srbbdefineservice.asmx 远程代码执行"
type = "RCE"
version = "未知"
path = "/srbbdefineservice.asmx"
detail = "未知"
fix = "未知"
date = "0707"
label = "0day"
verifier = "AdySec"
