vendor = "海信"
name = "海信智能公交企业管理系统SQL注入"
type = "SQL注入"
version = "未知"
path = "/YZSoft/Forms/XForm/BM/MaintainceManagement/BusDefAssgnManagement.aspx"
detail = "未知"
fix = "缺省规则可检出"
date = "0723"
label = "1day"
verifier = "AdySec"
