vendor = "用友"
name = "用友 U9 Cloud 远程代码执行"
type = "RCE"
version = "U9C 企业版、U9C 标准版"
path = "MachineKey硬编码"
detail = "MachineKey硬编码，构造ViewState反序列化"
fix = "未知"
date = "0714"
label = "0day"
verifier = "AdySec"
