vendor = "用友"
name = "用友BIP数据应用服务未授权访问"
type = "权限绕过"
version = "未知"
path = "/bi/api/SemanticModel/GetOlapConnectionList/"
detail = "/bi/api/SemanticModel/GetOlapConnectionList/?token=e30fe47a-f33e-463e-bc4a-843957ca88dd_263720ea7e397482da220115cae828_1214162142339"
fix = "老洞，有人当新洞发"
date = "0705"
label = "nday"
verifier = "AdySec"
