vendor = "畅捷通"
name = "畅捷通T+ /tplus/ajaxpro/Ufida.T.AA.FI.UIP.AccountAssociationEditListController.Ufida.T.AA.FI.UIP.ashx 命令执行"
type = "RCE"
version = "未知"
path = "/tplus/ajaxpro/Ufida.T.AA.FI.UIP.AccountAssociationEditListController.Ufida.T.AA.FI.UIP.ashx"
detail = "未知"
fix = "使用WAF封禁该地址"
date = "0730"
label = "1day"
verifier = "AdySec"
