vendor = "畅捷通"
name = "用友 畅捷通T+ getdecallusers 存在信息泄露"
type = "信息泄露"
version = "未知"
path = "/tplus/ajaxpro/Ufida.T.SM.Login.UIP.LoginManager,Ufida.T.SM.Login.UIP.ashx"
detail = "/tplus/ajaxpro/Ufida.T.SM.Login.UIP.LoginManager,Ufida.T.SM.Login.UIP.ashx?method=CheckPassword"
fix = "老的不能再老的洞"
date = "0705"
label = "nday"
verifier = "AdySec"
