vendor = "索贝"
name = "索贝内容管理系统 /sobey-mchEditor/mch/Articlelist/getList SQL注入"
type = "SQL注入"
version = "未知"
path = "/sobey-mchEditor/mch/Articlelist/getList"
detail = "未知"
fix = "缺省规则可检出"
date = "0730"
label = "nday"
verifier = "AdySec"
