vendor = "金和"
name = "金和OA IsHaveFTask.aspx 存在XXE"
type = "注入"
version = "未知"
path = "/c6/Jhsoft.Web.dailytaskmanage/IsHaveFTask.aspx"
detail = "未知"
fix = "未知"
date = "0715"
label = "0day"
verifier = "AdySec"
