vendor = "金蝶"
name = "金蝶云星空 BusinessDataService.BatchLoad.common.kdsvc 远程代码执行"
type = "RCE"
version = "未知"
path = "/Kingdee.BOS.ServiceFacade.ServicesStub.BusinessData.BusinessDataService.BatchLoad.common.kdsvc"
detail = "未知"
fix = "未知"
date = "0714"
label = "nday"
verifier = "AdySec"
