vendor = "360"
name = "360 新天擎终端安全管理系统存在信息泄露漏洞"
type = "信息泄露"
version = "未知"
path = "/runtime/admin_log_confcache"
detail = "/runtime/admin_log_confcache"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
