vendor = "F5"
name = "F5 BIG-IP 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/tmui/login.jsp /mgmt/tm/util/bash"
detail = "https://github.com/adysec/nuclei_poc/blob/ce5a47e163f5440c84dbfc0adb073ab35f562154/poc/cve/CVE-2023-46747.yaml"
fix = "使用WAF进行拦截"
date = "0722"
label = "nday"
