vendor = "LiveNVR"
name = "LiveNVR流媒体服务软件存在未授权访问漏洞"
type = "未授权访问"
version = "未知"
path = "/api/v1/device/channeltree?serial=&pcode"
detail = "/api/v1/device/channeltree?serial=&pcode"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "nday"
