vendor = "TOTOLINK"
name = "TOTOLINK-A3700R未授权访问漏洞"
type = "未授权访问"
version = "未知"
path = "/wizard.html"
detail = "http://ip/wizard.html http://ip/phone/wizard.html"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
