vendor = "九思"
name = "九思-OA-任意文件上传"
type = "RCE"
version = "未知"
path = "/jsoa/wpsforlinux/src/upload_l.jsp?openType="
detail = "/jsoa/wpsforlinux/src/upload_l.jsp?openType="
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
