vendor = "奇安信"
name = "网康 NS-ASG 信息泄露漏洞"
type = "信息泄露"
version = "未知"
path = "/configsave/manufacture-default.tar.gz"
detail = "/configsave/manufacture-default.tar.gz"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
