vendor = "宝兰德"
name = "宝兰德 BES 中间件 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/BesEJB/spark"
detail = "POST /BesEJB/spark HTTP/1.1 Host: 恶意序列化数据"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "0day"
