vendor = "广州图创"
name = "广州图创-图书馆集群管理系统-PermissionAC"
type = "未授权访问"
version = "未知"
path = "/interlibSSO/api/BrowseLogInterface?cmdACT=doDataFlowLogStatistic4ERM&sysid=1"
detail = "/interlibSSO/api/BrowseLogInterface?cmdACT=doDataFlowLogStatistic4ERM&sysid=1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
