vendor = "深信服"
name = "深信服 SSL VPN 短信验证码暴力猜解漏洞"
type = "未授权访问"
version = "M7.1~M7.6.9R4"
path = "未知"
detail = "深信服VPN问题，影响版本为M7.1~M7.6.9R4，在设备开启找回密码功能且已获知用户账号的前提下可能存在暴力破解验证码，从而修改用户密码的问题。"
fix = "针对受影响版本可下载升级SP SSL AW 02补丁包即可完成修复。如果没开启找回密码功能，则不受该问题影响。可以通过在短信验证码设置中，关闭【找回密码】功能，规避该问题。"
date = "0813"
label = "1day"
