vendor = "物聯網研究中心"
name = "私有云管理平台存在登录绕过漏洞"
type = "未授权访问"
version = "未知"
path = "/admin/#/login"
detail = "登陆界面抓包改返回响应的数据 {\"code\":1000,\"msg\":\"BscDYP2u0qLelgSB6XT1AxbULeN55ZayHYnmPEDnib4=\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0823"
label = "nday"
