vendor = "用友"
name = "用友 U8 cloud MonitorServlet 反序列化漏洞"
type = "RCE"
version = "未知"
path = "/service/~iufo/nc.bs.framework.mx.monitor.MonitorServlet"
detail = "POST /service/~iufo/nc.bs.framework.mx.monitor.MonitorServlet HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 恶意序列化数据"
fix = "使用WAF进行拦截"
date = "0722"
label = "nday"
