vendor = "积木"
name = "积木报表JeecgBoot被爆存在.net反序列化RCE 0day漏洞"
type = "RCE"
version = "未知"
path = "/jeecg-boot/jmreport/save?previousPage=xxx&jmLink=YWFhfHxiYmI="
detail = "/jeecg-boot/jmreport/save?previousPage=xxx&jmLink=YWFhfHxiYmI="
fix = "WAF封禁路路径，等待发布补丁"
date = "0731"
label = "1day"
