vendor = "金和"
name = "金和OA C6-GeneralXmlhttpPage.aspx存在SQL注入漏洞"
type = "SQL注入"
version = "C6"
path = "/C6/Jhsoft.Web.appraise/GeneralXmlhttpPage.aspx/?type=CheckAppraiseState&id="
detail = "/C6/Jhsoft.Web.appraise/GeneralXmlhttpPage.aspx/?type=CheckAppraiseState&id=1*"
fix = "WAF封禁路路径，等待发布补丁"
date = "0726"
label = "0day"
